### ISSUE TITLE
gnuplot: error while loading shared libraries: libpng16.so.16

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#1001]
Reported as https://github.com/peterjc/pico_galaxy/issues/17 where my MUMMER wrapper fails with a call to GNUPLOT missing libpng,

```
Fatal error: Exit code 1 ()
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "out.ntref" of length 388490
# construct suffix tree for sequence of length 388490
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 3884 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.05
# reading input file "/remote/RMS/users/galaxyd/files/051/dataset_51390.dat" of length 298399
# matching query-file "/remote/RMS/users/galaxyd/files/051/dataset_51390.dat"
# against subject-file "out.ntref"
# COMPLETETIME /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.15
# SPACE /opt/shed_tools/mummer/3.23/iuc/package_mummer_3_23/9ddc606546c3/mummer out.ntref 0.66
4: FINISHING DATAgnuplot: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
WARNING: Using outdated gnuplot, use v4.0 for best results
WARNING: Turning of --size option for compatibility
Reading delta file out.delta
Writing plot files /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.fplot, /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.rplot
Writing gnuplot script /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.gp
Rendering plot /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.png
gnuplot: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
WARNING: Unable to run 'gnuplot /tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.gp', Inappropriate ioctl for device
Traceback (most recent call last):
  File "/opt/shed_tools/toolshed.g2.bx.psu.edu/repos/peterjc/mummer/5f5a358b281f/mummer/tools/mummer/mummer.py", line 68, in <module>
    shutil.move(png_image, png_out)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/118873.1.galaxy.q/tmpAmGeOm/ref_qry.png'
```

@dwightkuo is using Galaxy v16.07 with my mummer wrapper and its dependencies installed via the Tool Shed, i.e.
- https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_mummer_3_23/tool_dependencies.xml
- https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_gnuplot_4_6/tool_dependencies.xml

**Comment by yhoogstrate** [comment]
Hi @peterjc, I have flagged this as low priority because it's using the tool-dependencies mechanism of Galaxy. Gnuplot and libpng are in conda/bioconda, I hope this helps?

**Comment by peterjc** [comment]
This is breaking on our local Galaxy now too (perhaps it was back in October 2016 but didn't notice), where we have not yet enabled conda for dependencies.

**Comment by peterjc** [comment]
Testing under planemo with latest Galaxy I'm seeing:

```
PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - ghostscript 9.10*

You can search for packages on anaconda.org with

    anaconda search -t conda ghostscript

You may need to install the anaconda-client command line client with

    conda install anaconda-client

```

There is a package in BioConda - https://anaconda.org/bioconda/ghostscript - but currently only version 9.18 and here we expect 9.10.

**Comment by peterjc** [comment]
Sadly things are not going smoothly in BioConda land for gnuplot, e.g.
https://github.com/bioconda/bioconda-recipes/pull/4655

I've logged a bug with MUMmer about ``WARNING: Using outdated gnuplot, use v4.0 for best results`` https://github.com/gmarcais/mummer/issues/14 and a pull request to fix the typo in ``WARNING: Turning of --size option for compatibility`` https://github.com/gmarcais/mummer/pull/13
