### ISSUE TITLE
SnpEff data manager error: No such file or directory

### ISSUE THREAD

**Issue by lifepillar** [galaxyproject/tools-iuc#1243]
I have installed the SnpEff data manager in my local Galaxy instance (release 17.01). When I run the SnpEff Databases or SnpEff Download jobs, I get this error:

```
Fatal error: Exit code 1 (Error)
Traceback (most recent call last):
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_snpeff/847b0f43c0e5/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py", line 76, in <module>
    main()
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_snpeff/847b0f43c0e5/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py", line 69, in main
    data_manager_dict = fetch_databases( data_manager_dict, target_directory, options.jar_path)
  File "/var/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_snpeff/847b0f43c0e5/data_manager_snpeff/data_manager/data_manager_snpEff_databases.py", line 26, in fetch_databases
    proc = subprocess.Popen( args=args, shell=False, cwd=snpEff_dir, stdout=databases_output.fileno() )
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Is there any configuration that must be performed by hand to make this working?

**Comment by lifepillar** [comment]
After some debugging, I have discovered that it's the Java executable that is not found. After installing Java system-wide, I was able to run the jobs.

I have been told [elsewhere](https://github.com/galaxyproject/galaxy/issues/3907#issuecomment-292887612) that system-wide dependencies should not be required, so you may want to check the dependencies for this tool.

**Comment by mvdbeek** [comment]
I think that should be fixed with https://github.com/galaxyproject/tools-iuc/pull/1252. If this happens again feel free to re-open the issue.
