### ISSUE TITLE
Problems with NCBI BLAST+ 2.5.0 and dependency errors installing from the tool shed

### ISSUE THREAD

**Issue by charesredhat** [galaxyproject/tools-iuc#1613]
Hi I installed NCBI BLAST+ 2.5.0 from the tool shed and I am using it as a dependency for a serotyping tool wrapper. But every time I run my tool it I get the following error 

main] Real time: 19.559 sec; CPU: 4.081 sec
[samopen] SAM header is present: 6 sequences.
makeblastdb: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
blastn: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/nfs/sw/apps/galaxy-dev/galaxy/tools/seqsero/libs/BWA_analysis_H_update_new_family_dependent.py", line 452, in <module>
    BWA_analysis(target,additional_file,data_base,mapping_mode,file_mode,z)
  File "/nfs/sw/apps/galaxy-dev/galaxy/tools/seqsero/libs/BWA_analysis_H_update_new_family_dependent.py", line 229, in BWA_analysis
    BWA_analysis(sra_name,additional_file,data_base2,mapping_mode,file_mode,z) #z=1 this time, z is the pointer for the seqeunce of run
  File "/nfs/sw/apps/galaxy-dev/galaxy/tools/seqsero/libs/BWA_analysis_H_update_new_family_dependent.py", line 236, in BWA_analysis
    family_test(final_fljB,"fljB",type,sra_name,for_fq,rev_fq,for_sai,rev_sai,sam,bam)
  File "/nfs/sw/apps/galaxy-dev/galaxy/tools/seqsero/libs/BWA_analysis_H_update_new_family_dependent.py", line 331, in family_test
    assembly(type,sra_name,for_fq,rev_fq,for_sai,rev_sai,sam,bam,database,database2,list_b_length,mapping_mode)
  File "/nfs/sw/apps/galaxy-dev/galaxy/tools/seqsero/libs/BWA_analysis_H_update_new_family_dependent.py", line 410, in assembly
    handle=open(database2+"_vs_"+sam+".xml")

And this is after I uninstalled NCBI BLAST+ 2.5.0 and then enabled conda channels 

conda_ensure_channels = iuc,bioconda,conda-forge,defaults,r

in the galaxy.ini and then cleared the conda cache and restarted galaxy and reinstalled the NCBI BLAST+ 2.5.0 and made sure the blast package was installed by conda.

This is all happening on a galley instance running on CentOS server. 

But on my local galaxy instance running on a Mac it works fine I don’t get any errors saying it can load makeblastdb or blastn.

Could it be a problem with conda and CentOS?

**Comment by nsoranzo** [comment]
@charesredhat ncbi_blast_plus is maintained at https://github.com/peterjc/galaxy_blast
