### ISSUE TITLE
MultiQC - error 'pytz' distribution was not found

### ISSUE THREAD

**Issue by vebaev** [galaxyproject/tools-iuc#1624]
After successful installation on MultiQC on Galaxy v17.09 it outputs error:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/bin/multiqc", line 4, in 
    __import__('pkg_resources').run_script('multiqc==1.2', 'multiqc')
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3144, in 
    @_call_aside
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytz' distribution was not found and is required by matplotlib
```

**Comment by lparsons** [comment]
I've just run into the same issue. I've used this same MultiQC installation before, so this is puzzling...

**Comment by mvdbeek** [comment]
Could be a problem with the conda package ... @lparsons is that for the current iuc version 1.3 ? Maybe it's worth bumping to 1.5 ?

**Comment by lparsons** [comment]
Yeah, I'm guessing that it is a problem with the conda package. It looks like Version 1.2.1 works, so maybe I'm wrong and 1.3 never worked... Updating to 1.5 may be worth it, but perhaps we can quickly fix the 1.3 conda package first.

**Comment by lparsons** [comment]
Well, looking at it, perhaps not. There is no easy way to fix the old bioconda recipe. I guess bumping to 1.5 is best.

**Comment by lparsons** [comment]
As a workaround, I was able to install `pytz` into the conda environment `__multiqc@1.3` manually (on the command line) and things work now.

**Comment by mvdbeek** [comment]
We can (and probably should) unearth the 1.3 multiqc recipe for the fix

**Comment by lparsons** [comment]
I'm not really sure that the 1.5 recipe works either, for that matter.

**Comment by mvdbeek** [comment]
https://github.com/bioconda/bioconda-recipes/blob/4d0cfc9b95ef9b478c26a686ffe7e8cdab311445/recipes/multiqc/meta.yaml
