### ISSUE TITLE
qiime data manager problem

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/tools-iuc#1667]
when executing the qiime data_manager I got: 

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 679, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 426, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1385, in finish
    self.tool.exec_after_process(self.queue.app, inp_data, out_data, param_dict, job=job)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tools/__init__.py", line 2213, in exec_after_process
    assert data_manager is not None, "Invalid data manager (%s) requested. It may have been removed before the job completed." % (data_manager_id)
AssertionError: Invalid data manager (toolshed.g2.bx.psu.edu/repos/iuc/data_manager_qiime_database_downloader/data_manager/data_manager_qiime_download/0.0.1) requested. It may have been removed before the job completed.
```

in the logs.

Is this a wrong path? Looks odd, since the actual path might be something like this `toolshed.g2.bx.psu.edu/repos/iuc/data_manager_qiime_database_downloader/cbe065fbd038/data_manager_qiime_database_downloader/data_manager/data_manager_qiime_download.xml` vut it has no version in it... ?

**Comment by bernt-matthias** [comment]
When I reran it it worked. Odd thing is that for the failed job the stdout and stderr were empty and the error code was 0.
