### ISSUE TITLE
Error while running DEXseq

### ISSUE THREAD

**Issue by bellenger-l** [galaxyproject/tools-iuc#1901]
Hello,

I tried to run DEXseq count reads with a DEXseq reference and a bam but I have the following error : 
```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/galaxy/tool_dependency/_conda/envs/mulled-v1-683dc60555985982bcd77839627baa1ef503a6a15fb8cf27f5b492bbedd69ac4/bin/dexseq_count.py", line 98, in 
    features[f.iv] += f
  File "python3/src/HTSeq/_HTSeq.pyx", line 451, in HTSeq._HTSeq.ChromVector.__iadd__
  File "python3/src/HTSeq/_HTSeq.pyx", line 466, in HTSeq._HTSeq.ChromVector.apply
  File "python3/src/HTSeq/_HTSeq.pyx", line 449, in HTSeq._HTSeq.ChromVector.__iadd__.addval
TypeError: unhashable type: 'GenomicFeature'
```

It seems that there is no test for DEXseq counts, (only for DEXseq prepare reference), so can you help me figure it out ? (After some research, a problem with the version of python is mentioned : https://support.bioconductor.org/p/106685/)

Best,
Lea

**Comment by mblue9** [comment]
@bellenger-l and @michelraymond this should be fixed now (xref: https://github.com/galaxyproject/tools-iuc/pull/1975) but let us know if not.
