### ISSUE TITLE
data_manager_bwa_mem_index_builder is failing

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/tools-iuc#1999]
```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bwa_mem_index_builder/46066df8813d/data_manager_bwa_mem_index_builder/data_manager/bwa_mem_index_builder.py", line 91, in <module>
    main()
  File "/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bwa_mem_index_builder/46066df8813d/data_manager_bwa_mem_index_builder/data_manager/bwa_mem_index_builder.py", line 84, in main
    build_bwa_index( data_manager_dict, options.fasta_filename, params, target_directory, dbkey, sequence_id, sequence_name, data_table_name=options.data_table_name or DEFAULT_DATA_TABLE_NAME )
  File "/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bwa_mem_index_builder/46066df8813d/data_manager_bwa_mem_index_builder/data_manager/bwa_mem_index_builder.py", line 45, in build_bwa_index
    proc = subprocess.Popen( args=args, shell=False, cwd=target_directory )
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
This turned up during ephemeris CI testing. Failure is consistent.
The previous revision (from 2016) works fine.

**Comment by mvdbeek** [comment]
Did you install bwa dependency ? This is working fine here.

**Comment by rhpvorderman** [comment]
I checked and found the dependency not installed. 
Please accept my deepest apologies for not investigating this to the hilt before reporting a bug.
