### ISSUE TITLE
Circos memory error ?

### ISSUE THREAD

**Issue by bellenger-l** [galaxyproject/tools-iuc#2049]
Hello, I am trying to use Circos on Galaxy Europe but I get this error when I tried to add an histogram with a wig file : 

```
Fatal error: Exit code 1 ()
INFO:root:Processing /data/dnb02/galaxy_db/files/007/284/dataset_7284181.dat.wig
Traceback (most recent call last):
  File "/usr/local/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/ef5f8bbf7730/circos/unified-histogram.py", line 88, in <module>
    func(idx, file_path)
  File "/usr/local/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/circos/ef5f8bbf7730/circos/unified-histogram.py", line 75, in wig
    data[region][position] = {}
MemoryError
WARNING:galaxy.model:Datatype class not found for extension 'tar.gz'
WARNING:galaxy.model:Datatype class not found for extension 'tar.gz'
WARNING:galaxy.model:Datatype class not found for extension 'tar.gz'
WARNING:galaxy.model:Datatype class not found for extension 'tar.gz'
WARNING:galaxy.model:Datatype class not found for extension 'tar.gz'
```

I don't know if it's a duplicate with this previous issue #1919 , but maybe it is something else because wig file test is working so I don't understand why my wig file isn't recognize by circos. I also tried to test with a smaller wig file, no success.

**Comment by bgruening** [comment]
Hi @bellenger-l! Are you using the "Circos Builder" tool? If so I have increased the memory for your tool. Please try again in 30min.

**Comment by bellenger-l** [comment]
Hi @bgruening, yes I am, I tested Circos this morning but I have the same error.

**Comment by bellenger-l** [comment]
@bgruening my mistake I forgot to change the span of my wig file, seems to work now.
Thanks for the quick answer.

Lea
