### ISSUE TITLE
MACS2 Fails with SAM input now -- intentional? Solutions to mitigate user confusion?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#2313]
Tool versions tested/history: 
* EU >> MACS2 callpeak Call peaks from alignment results (Galaxy Version 2.1.1.20160309.5) https://usegalaxy.eu:/u/jenj/h/test-macs2-bam-sam
* ORG >> MACS2 callpeak Call peaks from alignment results (Galaxy Version 2.1.1.20160309.4) https://usegalaxy.org:/u/jen/h/test-history-bowtie2-macs2-diffbind

MTS: https://toolshed.g2.bx.psu.edu/repository?repository_id=e984c9f63184b207

Problems: 
* The tool used to accept/work with SAM input. 
* Appears that the tool form was modified to explicitly state that BAM/BED/BAMPE is expected. 
* Most tools that accept BAM also accept SAM. 
* SAM datasets show up in the tool's select menu.
* User is not warning that SAM is not accepted -- on the tool form on in the GUI (most do not know how to review STDERR or what would be the actionable solution if they do find/review it). 
* **So ... it looks like a tool bug, even if intentional.**
* **Of note:** The "failed job" with SAM input that will always fail again automatically resubmittes at EU. Not sure how many times it will cycle, but is a waste of resource + confusing for users.

Can we think of some way to mitigate the issue? 
* Change the select to filter out SAM data? 
* Don't allow the job to submit if the input is not one of the three supported types (red select highlight with a warning like: "Input is not in BED, BAM, or BAMPE format"). 
* If those are not possible, at least the tool help should be modified -- with us knowing that "more help" text is nice but doesn't really help to _prevent_ usage problems like this. Nor auto-reruns.

Message in the red error dataset:
EU 
```
INFO  @ Mon, 25 Feb 2019 20:31:01: 
# Command line: callpeak -t /data/dnb02/galaxy_db/files/008/457/dataset_8457806.dat --name BAM-to-SAM_on_data_3__converted_SAM -c /data/dnb02/galaxy_db/files/008/457/dataset_8457807.dat --format BAM --gsize 2700000000
```

ORG 
```
/cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/MACS2/OptValidator.py:27: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
```

Error when bug report is click on: EU + ORG
```
Fatal error: Exit code 1 ()
```

Error in job info/stderr: EU capture, but same basic content at ORG
```
INFO  @ Mon, 25 Feb 2019 20:31:01: 
# Command line: callpeak -t /data/dnb02/galaxy_db/files/008/457/dataset_8457806.dat --name BAM-to-SAM_on_data_3__converted_SAM -c /data/dnb02/galaxy_db/files/008/457/dataset_8457807.dat --format BAM --gsize 2700000000 --keep-dup 1 --bdg --qvalue 0.05 --mfold 5 50 --bw 300
# ARGUMENTS LIST:
# name = BAM-to-SAM_on_data_3__converted_SAM
# format = BAM
# ChIP-seq file = ['/data/dnb02/galaxy_db/files/008/457/dataset_8457806.dat']
# control file = ['/data/dnb02/galaxy_db/files/008/457/dataset_8457807.dat']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Mon, 25 Feb 2019 20:31:01: #1 read tag files... 
INFO  @ Mon, 25 Feb 2019 20:31:01: #1 read treatment tags... 
Exception struct.error: 'unpack requires a string argument of length 4' in 'MACS2.IO.Parser.BAMParser.tsize' ignored
Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in <module>
    
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 57, in main
    
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 73, in run
  File "/usr/local/tools/_conda/envs/mulled-v1-9745eaf08708c75d5cb939b005b2fbbcc13ccefcb86602af9e1bf012d47be274/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 399, in load_tag_files_options
  File "MACS2/IO/Parser.pyx", line 880, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13703)
  File "MACS2/IO/Parser.pyx", line 893, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13111)
  File "MACS2/IO/Parser.pyx", line 877, in MACS2.IO.Parser.BAMParser.get_references (MACS2/IO/Parser.c:12886)
struct.error: unpack requires a string argument of length 4
```

**Comment by jennaj** [comment]
Backtrack for Main update if/when modified: https://github.com/galaxyproject/usegalaxy-playbook/issues/192

**Comment by jmchilton** [comment]
@jennaj and I discussed this and it seems like if this tool just removed sam as an input option, implicit conversion work make SAM work properly.

**Comment by mvdbeek** [comment]
uncompressed sam is a crime anyway, we can remove this
