### ISSUE TITLE
GEMINI Data Manager is not Python 3 compatible

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/tools-iuc#2408]
After successfully downloading, it fails with:

```pytb
/cvmfs/test.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_gemini_database_downloader/f57426daa04d/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(fi)
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_gemini_database_downloader/f57426daa04d/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py", line 91, in <module>
    main()
  File "/cvmfs/test.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_gemini_database_downloader/f57426daa04d/data_manager_gemini_database_downloader/data_manager/data_manager_gemini_download.py", line 87, in main
    out.write( json.dumps( data_manager_dict ) )
TypeError: a bytes-like object is required, not 'str'
```

Assuming many DMs are copied from others, there may be other DMs with the same problem.

**Comment by nsoranzo** [comment]
As mentioned in the original ticket, this will be fixed by https://github.com/galaxyproject/tools-iuc/pull/2032 .
