### ISSUE TITLE
Jbrowse 1.16.5+galaxy3 perl mismatch

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/tools-iuc#2495]
After installing JBrowse 1.16.5+galaxy3 I get the following error when trying to execute JBrowse. Installation was using conda to satisfy dependencies.

```
Fatal error: Exit code 1 ()
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xdb00080)
Traceback (most recent call last):
  File "/sc1/groups/md/RMS/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/6b774e9d6387/jbrowse/jbrowse.py", line 998, in <module>
    gencode=root.find('metadata/gencode').text
  File "/sc1/groups/md/RMS/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/6b774e9d6387/jbrowse/jbrowse.py", line 364, in __init__
    self.process_genomes()
  File "/sc1/groups/md/RMS/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/6b774e9d6387/jbrowse/jbrowse.py", line 416, in process_genomes
    '--indexed_fasta', os.path.realpath(local_genome)])
  File "/sc1/groups/md/RMS/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/6b774e9d6387/jbrowse/jbrowse.py", line 384, in subprocess_check_call
    subprocess.check_call(command, cwd=self.outdir)
  File "/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85959/conda-env/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['perl', '/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85959/conda-env/opt/jbrowse/bin/prepare-refseqs.pl', '--trackConfig', '{"metadata": {"dataset_id": "46637f7fd95bfe3b", "dataset_hid": "41", "dataset_size": "2.8 MB", "dataset_edam_format": "<a target=\\"_blank\\" href=\\"http://edamontology.org/format_1929\\">fasta</a>", "dataset_file_ext": "fasta", "history_id": "c0f35771671e77b6", "history_user_email": "<a href=\\"mailto:dwight.kuo@roche.com\\">dwight.kuo@roche.com</a>", "history_user_id": "1", "history_display_name": "<a target=\\"_blank\\" href=\\"http://localhost/history/view/c0f35771671e77b6\\">imported: 190715_M02091_0055_000000000-CHWRC</a>", "metadata_dbkey": "?", "metadata_data_lines": "47928", "metadata_sequences": "53", "tool_tool_id": "bbnormspades", "tool_tool_version": "3.9.0", "tool_tool": "<a target=\\"_blank\\" href=\\"http://localhost/datasets/46637f7fd95bfe3b/show_params\\">bbnormspades</a>"}}', '--indexed_fasta', '/sc1/groups/md/RMS/galaxy/database/jobs_directory/085/85959/working/genome.fasta']' returned non-zero exit status 1.
```

**Comment by abretaud** [comment]
Sorry for the late reply, I missed this issue
Do you still have this error? I have made several installs of this tool in different conditions and never had it... Anything unusual in the PATH?

**Comment by dwightkuo** [comment]
I tried uninstalling and installing the newest version and now get these
errors in the galaxy.log file:


PackageNotFoundError: Package not found: '' Dependencies missing in current
linux-64 channels:
  - jbrowse 1.16.5* -> gff3sort -> perl-data-match -> perl
>=5.26.2,<5.26.3.0a0 -> libgcc-ng >=7.3.0
  - jbrowse 1.16.5* -> libstdcxx-ng >=7.3.0
  - samtools 1.9* -> libdeflate >=1.0,<1.1.0a0 -> libgcc-ng >=4.9
  - samtools 1.9* -> curl >=7.64.0,<8.0a0 -> krb5 >=1.16.3,<1.17.0a0 ->
libstdcxx-ng >=4.9
  - pyyaml 3.13* -> libgcc-ng >=4.9
  - pyyaml 3.13* -> python >=3.7,<3.8.0a0 -> libstdcxx-ng >=7.3.0
  - tabix 0.2.6* -> libgcc-ng >=4.9

Close matches found; did you mean one of these?

    libgcc-ng: libgcc, libclang
    libgcc-ng: libgcc, libclang

You can search for packages on anaconda.org with

    anaconda search -t conda libstdcxx-ng

(and similarly for the other packages)

**Comment by abretaud** [comment]
That's odd, what gives the command `conda info`? Maybe a bad version of conda, or some problem with channel configuration?

**Comment by dwightkuo** [comment]
This is what I get when I create an tool xml that runs "conda info" i.e.:
  <command >
        conda info;
  </command>

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /sc1/groups/md/RMS/sw/miniconda2  (writable)
    default environment : /sc1/groups/md/RMS/sw/miniconda2
       envs directories : /sc1/groups/md/RMS/sw/miniconda2/envs
                          /sc1/groups/md/RMS/conda/envs
                          /home/rssmd/.conda/envs
          package cache : /sc1/groups/md/RMS/sw/miniconda2/pkgs
                          /home/rssmd/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/rssmd/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13
Linux/3.10.0-957.5.1.el7.x86_64 CentOS Linux/7.6.1810 glibc/2.17
                UID:GID : 86790:20

**Comment by abretaud** [comment]
I think your conda install would deserve an update, 4.3.11 is old. [Galaxy 19.09 uses 4.6.14](https://github.com/galaxyproject/galaxy/blob/release_19.09/lib/galaxy/tool_util/deps/conda_util.py#L38) now, 4.7.12 works well on my instance too.

Also what is the value of `conda_ensure_channels` in your galaxy.yml?

It would good to have the full log of the conda install, including the command line, to see what's going wrong

**Comment by dwightkuo** [comment]
conda_ensure_channels is set to the default in galaxy.yml:
#conda_ensure_channels: 'iuc,bioconda,conda-forge,defaults'

The only relevant lines from the galaxy.log appears to be these:
< galaxy.tools.deps.conda_util DEBUG 2019-10-31 09:41:49,009
[p:17389,w:1,m:0] [uWSGIWorker1Core3] Executing command:
/sc1/groups/md/RMS/galaxy/database/dependencies/_conda/bin/conda create -y
--override-channels --channel iuc --channel bioconda --channel conda-forge
--channel defaults --name
mulled-v1-0f3b50d15b94d6d7f5cb012d8d0f377709890eb1028c2404c5097b7fa59b4f1e
jbrowse=1.16.5 python=2.7 biopython=1.72 bcbiogff=0.6.4 samtools=1.9
pyyaml=3.13 tabix=0.2.6
....
< Solving package specifications: .
<
<
< PackageNotFoundError: Package not found: '' Dependencies missing in
current linux-64 channels:
<   - jbrowse 1.16.5* -> gff3sort -> perl-data-match -> perl
>=5.26.2,<5.26.3.0a0 -> libgcc-ng >=7.3.0
<   - jbrowse 1.16.5* -> libstdcxx-ng >=7.3.0
<   - samtools 1.9* -> libdeflate >=1.0,<1.1.0a0 -> libgcc-ng >=4.9
<   - samtools 1.9* -> curl >=7.64.0,<8.0a0 -> krb5 >=1.16.3,<1.17.0a0 ->
libstdcxx-ng >=7.3.0
<   - pyyaml 3.13* -> libgcc-ng >=4.9
<   - pyyaml 3.13* -> python >=3.7,<3.8.0a0 -> libstdcxx-ng >=7.3.0
<   - tabix 0.2.6* -> libgcc-ng >=4.9
<
< Close matches found; did you mean one of these?
<
<     libgcc-ng: libgcc, libclang
<     libgcc-ng: libgcc, libclang
<
< You can search for packages on anaconda.org with
<
<     anaconda search -t conda libstdcxx-ng
<
< (and similarly for the other packages)
<

When I try to install this is the screen I get. Is this doesn't seem
normal. The "None" for jbrowse, samtools, pyyaml and tabix...
The following tool dependencies are required by the current repository
DependencyVersionCurrent Installation Status
python 2.7  Installed through Conda
biopython 1.72  Installed through Conda
bcbiogff 0.6.4  Installed through Conda
jbrowse None
samtools None
pyyaml None
tabix None
Confirm dependency installation

By default Galaxy will install all needed dependencies for the repository.
See the dependency resolver documentation
<https://docs.galaxyproject.org/en/master/admin/dependency_resolvers.html>.

You can control how dependencies are installed (this is an advanced option,
if in doubt, use the default) Hide Details

When available, install Conda
<https://docs.galaxyproject.org/en/master/admin/conda_faq.html> managed
tool dependencies?
Select to automatically install tool dependencies via Conda.
