### ISSUE TITLE
JBrowse tool fails for empty gff3 tracks in a workflow

### ISSUE THREAD

**Issue by MoffMade** [galaxyproject/tools-iuc#3180]
When using the JBrowse tool in a large workflow, we have a couple of analysis paths that can end in an empty file when added as an evidence track depending on the features found in the given sequence. This causes an issue, now, as the JBrowse tool fails and interrupts the workflow run. I've been able to patch it with ensuring the input file ends up with an "empty" gff3 file containing only the "##gff-version 3" line but I think a better interaction would be for the tool to skip empty files instead of ungracefully failing. 

A previous version of the tool had this functionality, but since we've updated to the IUC version instead of an old custom fork we've had this occur. Seems it got added with the use of gff3sort.pl for the tabix index sorting.

Here is the exact error traceback we've gotten:
```
ERROR:jbrowse:cd /galaxy/database/jobs_directory/000/290/290155/working/dataset_516206_files && gff3sort.pl --precise '/media/nfs-galaxy/000/516/dataset_516182.dat' | grep -v "^$" > '/galaxy/database/jobs_directory/000/290/290155/working/dataset_516206_files/data/raw/e8d7a89af30eca612ea59a77d53ff185_2.gff'
ERROR:jbrowse:
ERROR:jbrowse:
Traceback (most recent call last):
  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/17359b808b01/jbrowse/jbrowse.py", line 1267, in <module>
    for key in keys:
  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/17359b808b01/jbrowse/jbrowse.py", line 914, in process_annotations
    track['conf']['options']['gff'])
  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/17359b808b01/jbrowse/jbrowse.py", line 672, in add_gff
    self._sort_gff(data, dest)
  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/17359b808b01/jbrowse/jbrowse.py", line 654, in _sort_gff
    self.subprocess_popen(cmd)
  File "/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/17359b808b01/jbrowse/jbrowse.py", line 394, in subprocess_popen
    raise RuntimeError("Command failed with exit code %s" % (retcode))
RuntimeError: Command failed with exit code 1
```

**Comment by MoffMade** [comment]
We've done some in-house development on the tool/wrapper. I'll see if we can get a PR opened with the changes for review
