### ISSUE TITLE
Hisat2 produces only 1 output when used outside of collections with multiple inputs

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#326]
The hisat2 wrapper is working nicely, except that feeding in multiple unpaired single fastq files (not in a collection) produces only 1 output, while I would expect  that I get 1 output file per input file (as would happen with a dataset collection). Feature or bug? Ping @davebx

**Comment by mvdbeek** [comment]
Also, there seems to be a bug in specifying spliced_alignment_options:
```
Traceback (most recent call last):
  File "/home/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/home/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 862, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/home/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 422, in build
    raise e
NotFound: cannot find 'no_spliced_alignment' while searching for 'spliced_options.no_spliced_alignment'
```

**Comment by davebx** [comment]
@mvdbeek Thanks, I'll have a look.

**Comment by bgruening** [comment]
I think we can close this.

**Comment by mvdbeek** [comment]
Indeed, thanks.
