### ISSUE TITLE
latest update of optitype fails with an error 

### ISSUE THREAD

**Issue by ksenia-krasheninnikova** [galaxyproject/tools-iuc#3387]
Hello,

Optitype package (toolshed.g2.bx.psu.edu/repos/jjohnson/optitype/optitype/1.3.2) was installed into a local galaxy server from the toolshed. It was run on the paired-end data in the DNA mode and failed with the following error:

Traceback (most recent call last):
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/bin/OptiTypePipeline.py", line 129, in <module>
    from model import OptiType
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/share/optitype-1.3.2-3/model.py", line 19, in <module>
    from pyomo.environ import ConcreteModel, Set, Param, Var, Binary, Objective, Constraint, ConstraintList, maximize
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 97, in <module>
    _import_packages()
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 81, in _import_packages
    raise ImportError(msg)
ImportError: pyomo.environ failed to import pyomo.core.plugins:
Original ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
Traceback:
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 69, in _import_packages
    _do_import(pname)
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 19, in _do_import
    __import__(pkg_name, globals(), locals(), [], -1)
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/home/ksenia/melanoma/galaxy/galaxy/database/dependencies/_conda/envs/__optitype@1.3.2/lib/python2.7/site-packages/pyutilib/enum/__init__.py", line 18, in <module>
    package) that supersedes this library.""")

A fix or possible solution would be most appreciated.

Thank you!

Best regards,

Ksenia

**Comment by bernt-matthias** [comment]
Hi @ksenia-krasheninnikova this tool is not part of this repository. 

Could you try to ping jjohnson at https://gitter.im/GalaxyProteomics/Lobby or open the issue over here https://github.com/jj-umn/galaxytools/tree/master/optitype?

Since this looks like a problem with the (bio)conda package https://github.com/bioconda/bioconda-recipes/ .. but they already have a newer version than used in the Galaxy tool. 

I'm closing the issue here.
