### ISSUE TITLE
pygenometracks error

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#3394]
just saw that in our logs flying by:

```
Dec 22 15:56:38 sn04.bi.uni-freiburg.de uwsgi[2869466]: galaxy.webapps.base.webapp DEBUG 2020-12-22 15:56:38,139 [p:2874092,w:3,m:0] [uWSGIWorker3Core0] Error parsing locale 'en-IT'. <class 'babel.core.UnknownLocaleError'>: unknown locale 'en_IT'
Dec 22 15:56:38 sn04.bi.uni-freiburg.de uwsgi[2869466]: galaxy.webapps.base.webapp DEBUG 2020-12-22 15:56:38,315 [p:798741,w:2,m:0] [uWSGIWorker2Core0] Error parsing locale 'en-IT'. <class 'babel.core.UnknownLocaleError'>: unknown locale 'en_IT'
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: galaxy.web.framework.decorators ERROR 2020-12-22 15:56:41,422 [p:798741,w:2,m:0] [uWSGIWorker2Core0] Uncaught exception in exposed API method:
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: Traceback (most recent call last):
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/web/framework/decorators.py", line 294, in decorator
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: rval = func(self, trans, *args, **kwargs)
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/webapps/galaxy/api/tools.py", line 123, in build
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: return tool.to_json(trans, kwd.get('inputs', kwd))
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/tools/__init__.py", line 2201, in to_json
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: 'state_inputs'  : params_to_strings(self.inputs, state_inputs, self.app, use_security=True, nested=True),
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/tools/parameters/__init__.py", line 208, in params_to_strings
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: value = params[key].value_to_basic(value, app, use_security=use_security)
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/tools/parameters/grouping.py", line 102, in value_to_basic
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: rval_dict[input.name] = input.value_to_basic(d[input.name], app, use_security)
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/tools/parameters/grouping.py", line 670, in value_to_basic
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: current_case = rval['__current_case__'] = self.get_current_case(value[self.test_param.name])
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: File "lib/galaxy/tools/parameters/grouping.py", line 665, in get_current_case
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: raise ValueError("No case matched value:", self.name, str_value)
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: ValueError: ('No case matched value:', 'track_file_style_conditional', 'None')
Dec 22 15:56:41 sn04.bi.uni-freiburg.de uwsgi[2869466]: 141.2.72.106 - - [22/Dec/2020:15:56:38 +0200] "POST /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.5/build HTTP/1.1" 500 - "https://usegalaxy.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

```

**Comment by mvdbeek** [comment]
That (also?) looks like something Galaxy shouldn't throw a 500 for. Do you happen to have the request payload ?

**Comment by bgruening** [comment]
I don't have a payload, sorry. I just say that in our web handlers :(
