### ISSUE TITLE
Shorah error

### ISSUE THREAD

**Issue by JayanthiGangiredla** [galaxyproject/tools-iuc#3516]
Hi I was trying to run Shorah, but it's giving me this error: Please help me fix it.

--- Logging error ---
Traceback (most recent call last):
  File "/dep/_conda/envs/__shorah@1.1.3/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/dep/_conda/envs/__shorah@1.1.3/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/dep/_conda/envs/__shorah@1.1.3/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/dep/_conda/envs/__shorah@1.1.3/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/dep/_conda/envs/__shorah@1.1.3/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 429, in <module>
    args.s, args.region, args.diversity)
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 350, in main
    ret_diri = run_child(diri_exe, diri_args)
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 63, in run_child
    amplog.error("Child %s terminated by signal" % exe_name, retcode)
Message: 'Child /dep/_conda/envs/__shorah@1.1.3/bin/diri_sampler terminated by signal'
Arguments: (1,)
Traceback (most recent call last):
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 429, in <module>
    args.s, args.region, args.diversity)
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 354, in main
    run_diagnostics(win_file, n_reads)
  File "/dep/_conda/envs/__shorah@1.1.3/bin/amplian.py", line 88, in run_diagnostics
    if new_clusters < q:
UnboundLocalError: local variable 'new_clusters' referenced before assignment

**Comment by bernt-matthias** [comment]
Looks a bit like a bug in shorah itself. Maybe you can report the error over there: https://github.com/cbg-ethz/shorah/
