### ISSUE TITLE
jbrowse tool not working

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/tools-iuc#357]
This might be related to #356, but the jbrowse tool is not working with the stable galaxy install, here is the stack trace (note the two errors):

```
Fatal error: Exit code 1 ()
Can't open perl script "bin/prepare-refseqs.pl": No such file or directory
Traceback (most recent call last):
  File "/data/homes/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b6a0e126dbee/jbrowse/jbrowse.py", line 326, in <module>
    genome=os.path.realpath(args.genome.name),
  File "/data/homes/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b6a0e126dbee/jbrowse/jbrowse.py", line 64, in __init__
    self.process_genome()
  File "/data/homes/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b6a0e126dbee/jbrowse/jbrowse.py", line 77, in process_genome
    '--fasta', self.genome_path])
  File "/data/homes/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/b6a0e126dbee/jbrowse/jbrowse.py", line 68, in subprocess_check_call
    subprocess.check_call(command, cwd=self.jbrowse_dir)
  File "/data/homes/galaxy/galaxy/dependencies/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['perl', 'bin/prepare-refseqs.pl', '--fasta', '/data/homes/galaxy/galaxy/database/files/007/dataset_7446.dat']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/data/homes/galaxy/galaxy/database/job_working_directory/004/4534/set_metadata_kL0hZf.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/data/homes/galaxy/galaxy/lib/galaxy_ext/metadata/set_metadata.py", line 27, in <module>
    import galaxy.model.mapping  # need to load this before we unpickle, in order to setup properties assigned by the mappers
  File "/data/homes/galaxy/galaxy/lib/galaxy/model/__init__.py", line 33, in <module>
    import galaxy.datatypes.registry
  File "/data/homes/galaxy/galaxy/lib/galaxy/datatypes/registry.py", line 8, in <module>
    import data
  File "/data/homes/galaxy/galaxy/lib/galaxy/datatypes/data.py", line 18, in <module>
    import dataproviders
  File "/data/homes/galaxy/galaxy/lib/galaxy/datatypes/dataproviders/__init__.py", line 29, in <module>
    import dataset
  File "/data/homes/galaxy/galaxy/lib/galaxy/datatypes/dataproviders/dataset.py", line 14, in <module>
    from galaxy.util import sqlite
  File "/data/homes/galaxy/galaxy/lib/galaxy/util/sqlite.py", line 1, in <module>
    import sqlite3
  File "/data/homes/galaxy/galaxy/dependencies/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/data/homes/galaxy/galaxy/dependencies/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

```

**Comment by erasche** [comment]
Hi @tiagoantao, I'm afraid the jbrowse v0.3 was released with little-to-no testing beforehand, the release is somewhat broken (especially the dependencies). The next update will have significantly better testing. In your error I'm concerned by the part:

> Can't open perl script "bin/prepare-refseqs.pl": No such file or directory

that definitely shouldn't happen. If you're eager to test out JBrowse in Galaxy, you can install it manually (and all 2 dozen or so dependencies) and I can walk you through that, otherwise I hope to have the next JBrowse iteration out by the end of November.

**Comment by erasche** [comment]
Hi @tiagoantao sorry for the delay. The latest version of JBrowse-in-Galaxy is being placed on the main toolshed now. It should solve all of these issues. :)

**Comment by tiagoantao** [comment]
@erasche This is amazing, thanks!
