### ISSUE TITLE
package_matplotlib_1_4 is missing dependency six

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#358]
```
Traceback (most recent call last):
  File "/Users/marius/src/shed_tools/testtoolshed.g2.bx.psu.edu/repos/mvdbeek/dapars/a5d8b08af089/dapars/dapars.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/Users/marius/src/shed_tools/matplotlib/1.4/iuc/package_matplotlib_1_4/fb53242ebfbe/lib/python/matplotlib-1.4.3-py2.7-macosx-10.10-x86_64.egg/matplotlib/__init__.py", line 105, in <module>
    import six
ImportError: No module named six
```

**Comment by bgruening** [comment]
This is fixed in https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_python_2_7_matplotlib_1_4

For the other package we could add a new download action and install a second library ... what do you think?

**Comment by bgruening** [comment]
@mvdbeek can we close this in favour of the other package?

**Comment by mvdbeek** [comment]
Sure
