### ISSUE TITLE
BUSCO Test #5 failing under Galaxy 21.05

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/tools-iuc#3688]
Hi!
We are supposed to open issues for each failing tool test under 21.05 as part of the release testing plan.

This `Test #5` seems to have problems trying to locate a file.

### Standard Error
````
Job in error state.. tool_id: busco, exit_code: 1, stderr: CRITICAL:	Unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/busco/run_BUSCO.py", line 329, in run_BUSCO
    config_manager.load_busco_config(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoLogger.py", line 65, in wrapped_func
    self.retval = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/busco/ConfigManager.py", line 59, in load_busco_config
    self.config.validate()
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoConfig.py", line 387, in validate
    self._init_downloader()
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoConfig.py", line 91, in _init_downloader
    self.downloader = BuscoDownloadManager(self)
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoDownloadManager.py", line 50, in __init__
    self._load_versions()
  File "/usr/local/lib/python3.9/site-packages/busco/BuscoDownloadManager.py", line 60, in _load_versions
    with open(versions_file, "r") as v_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpy0i8x2or/job_working_directory/000/121/working/busco_downloads/file_versions.tsv'
````

### Standard Output
````
INFO:	***** Start a BUSCO v5.0.0 analysis, current time: 05/17/2021 10:52:08 *****
INFO:	Configuring BUSCO with local environment
INFO:	Mode is genome
INFO:	Input file is /tmp/tmpy0i8x2or/files/4/9/4/dataset_494450ed-d598-4721-a250-276fe4f8c30e.dat
INFO:	Downloading information on latest versions of BUSCO data...
````

More details here: https://github.com/galaxyproject/tools-iuc/actions/runs/848103510

**Comment by davelopez** [comment]
See https://github.com/galaxyproject/tools-iuc/issues/3666#issuecomment-847679647
