### ISSUE TITLE
plasflow 1.1.0 tools fails planemo test

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/tools-iuc#3711]
How to reproduce:

1. run `planemo test plasflow.xml`
2. Receive output like the following:

```
| 2 - PlasFlow on data 1: Probability table (HID - NAME) 
| Dataset State:
|  error
| Dataset Blurb:
|  error
| Dataset Info:
|  Importing sequences
|  Imported  [1] 2
|  sequences
|  Calculating kmer frequencies using kmer 5
|  Transforming kmer frequencies
|  Traceback (most recent call last):
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/python/__
| Peek:
|  *Peek unavilable.*
| Dataset Job Standard Output:
|  Importing sequences
|  Imported  [1] 2
|  sequences
|  Calculating kmer frequencies using kmer 5
|  Transforming kmer frequencies
| Dataset Job Standard Error:
|  Traceback (most recent call last):
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
|  from tensorflow.core.framework.graph_pb2 import *
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
|  from google.protobuf import descriptor as _descriptor
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
|  from google.protobuf.pyext import _message
|  ImportError: /home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
|  During handling of the above exception, another exception occurred:
|  Traceback (most recent call last):
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/bin/PlasFlow.py", line 261, in <module>
|  vote_proba = vote_class.predict_proba(input_data)
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/bin/PlasFlow.py", line 215, in predict_proba
|  self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/bin/PlasFlow.py", line 215, in <listcomp>
|  self.probas_ = [clf.predict_proba_tf(X) for clf in self.clfs]
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/bin/PlasFlow.py", line 171, in predict_proba_tf
|  import tensorflow as tf
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
|  from tensorflow.python import *
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 58, in <module>
|  raise ImportError(msg)
|  ImportError: Traceback (most recent call last):
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
|  from tensorflow.core.framework.graph_pb2 import *
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
|  from google.protobuf import descriptor as _descriptor
|  File "/home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
|  from google.protobuf.pyext import _message
|  ImportError: /home/pvh/miniconda3/envs/__plasflow@1.1.0/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
|  Error importing tensorflow.  Unless you are using bazel,
|  you should not try to import tensorflow from its source directory;
|  please exit the tensorflow source tree, and relaunch your python interpreter
|  from there.
```

This is with plasflow installed from bioconda (where the bioconda recipe is from https://github.com/bioconda/bioconda-recipes/pull/10326). This seems to be noted as a problem upstream - see WIP PR https://github.com/bioconda/bioconda-recipes/pull/27766 from @bernt-matthias. I'm opening this issue though to note that this tool is, for now, broken. Thanks to @JayanthiGangiredla for noting this.

**Comment by bernt-matthias** [comment]
https://github.com/smaegol/PlasFlow/issues/39

**Comment by bernt-matthias** [comment]
Should be fixed for now

**Comment by JayanthiGangiredla** [comment]
Thank you so much!

From: M Bernt ***@***.***>
Date: Saturday, January 21, 2023 at 8:21 AM
To: galaxyproject/tools-iuc ***@***.***>
Cc: Gangiredla, Jayanthi. ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [galaxyproject/tools-iuc] plasflow 1.1.0 tools fails planemo test (#3711)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Should be fixed for now

**Comment by JayanthiGangiredla** [comment]
Hi,

Recently, there is a sra_tools v3 update on galaxy repo from iuc, which requires galaxy version +22.01. Currently, our Galaxytrakr server runs on 21.09. Can you please let us know if there is a way, we can update sra_tools on galaxy version 21.09? This will be helpful until we make our next galaxy version upgrade.

Thanks,
Jayanthi

>

**Comment by bernt-matthias** [comment]
@JayanthiGangiredla all ideas that come to my mind seem more complicated than an update.

The question seems not related to this issue. It would have been better to open a new issue.
