### ISSUE TITLE
CI allowed an invalid XML to pass linting

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#3831]
https://github.com/galaxyproject/tools-iuc/pull/3703 went green even though in logs planemo clearly found invalid xml

```
Error loading tool with path /tmp/planemo_tmp_n5884x1x/5a91104912b0855671f23ca510306346/tb_variant_filter/tb_variant_filter.xml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/galaxy/tool_util/loader_directory.py", line 109, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
  File "/tmp/planemo_tmp_n5884x1x/5a91104912b0855671f23ca510306346/tb_variant_filter/tb_variant_filter.xml", line 138
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: assert_stderr line 136 and assert_stdout, line 138, column 39
Failed linting
+Linting tool /home/runner/work/tools-iuc/tools-iuc/tools/tb_variant_filter/tb_variant_filter.xml
Could not lint /tmp/planemo_tmp_n5884x1x/5a91104912b0855671f23ca510306346/tb_variant_filter/tb_variant_filter.xml due to malformed xml.
+ mapfile -t TOOL_ARRAY
+ '[' lint == test ']'
+ '[' lint == combine ']'
+ '[' lint == check ']'
+ '[' lint == deploy ']'
```

**Comment by mvdbeek** [comment]
That's been fixed since then: https://github.com/galaxyproject/planemo-ci-action/pull/19

**Comment by martenson** [comment]
Awesome, thanks for closing!
