### ISSUE TITLE
add recentrifuge tool

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#4482]
I made a recentrifuge wrapper to suggest this tool to the IUC and galaxy community

- [x]  Create the xml file
- [x]  Create the .shed.yaml
- [x]  Test the xml file
- [x] Submit to the IUC team 
- [ ]  Reviewing accepted

**Comment by bgruening** [comment]
Lovely! :)

**Comment by pimarin** [comment]
I encount a problem when apply the planemo test.

- [x] planemo shed_lint --tools --owner pimarin
- [x] planemo shed_create --shed_target testtoolshed --owner pimarin
- [x] planemo shed_diff --shed_target testtoolshed --owner pimarin
- [x] planemo shed_update --check_diff --shed_target testtoolshed --owner pimarin
- [ ] planemo shed_test --shed_target testtoolshe --owner pimarin :

```Requirement already satisfied: watchdog in /home/pierre/planemo/lib/python3.7/site-packages (from -r /dev/stdin (line 1)) (2.1.6)
The Galaxy client build is being skipped due to the SKIP_CLIENT_BUILD environment variable.
Activating virtualenv at /home/pierre/.planemo/gx_venv_3
./run_tests.sh: /home/pierre/.planemo/gx_venv_3/bin/pytest : /home/pierre/.planemo/gx_venv_3/bin/python : mauvais interpréteur: Aucun fichier ou dossier de ce type
Testing complete. HTML report is in "run_installed_tests.html".
Cannot locate xUnit report [/tmp/tmprzx_9ojd/xunit.xml] for tests - required to build planemo report and summarize tests.
Traceback (most recent call last):
  File "/home/pierre/planemo/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/pierre/planemo/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pierre/planemo/lib/python3.7/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/pierre/planemo/lib/python3.7/site-packages/planemo/commands/cmd_shed_test.py", line 44, in cli
    **kwds
  File "/home/pierre/planemo/lib/python3.7/site-packages/planemo/galaxy/test/actions.py", line 116, in run_in_config
    _check_test_outputs(xunit_report_file_tracker, structured_report_file_tracker)
  File "/home/pierre/planemo/lib/python3.7/site-packages/planemo/galaxy/test/actions.py", line 330, in _check_test_outputs
    raise Exception(message)
Exception: Cannot locate xUnit report [/tmp/tmprzx_9ojd/xunit.xml] for tests - required to build planemo report and summarize tests.
```

I already received this error and just use python 3.7 instead of 3.9 or 3.10 fixed the problem, but even if i tried with different python version, I have the same problem.

**Comment by gallardoalba** [comment]
Closed by https://github.com/galaxyproject/tools-iuc/pull/4540
