### ISSUE TITLE
hamronize_tool bug with summarize

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/tools-iuc#4547]
I have a problem using the hamronize tool in my workflow.
- [X] Use the hamronize for multiple tsv files --> it workstsv 
- [ ] Use Summarize to have a final report with all previous transformed tsv files --> failed
The summarize tools wait .tsv AND .json instead of AND/OR.

```
ln -s '/tmp/tmpdsvmli6t/files/000/dataset_13.dat' ./report_0.tsv && ln -s '/tmp/tmpdsvmli6t/files/000/dataset_17.dat' ./report_1.tsv &&  hamronize summarize --summary_type interactive --output output.html *.tsv *.json
```
```
Traceback (most recent call last):
  File "/home/pierre/anaconda3/envs/__hamronization@1.0.3/bin/hamronize", line 10, in <module>
    sys.exit(main())
  File "/home/pierre/anaconda3/envs/__hamronization@1.0.3/lib/python3.10/site-packages/hAMRonization/hamronize.py", line 7, in main
    hAMRonization.Interfaces.generic_cli_interface()
  File "/home/pierre/anaconda3/envs/__hamronization@1.0.3/lib/python3.10/site-packages/hAMRonization/Interfaces.py", line 278, in generic_cli_interface
    hAMRonization.summarize.summarize_reports(args.hamronized_reports,
  File "/home/pierre/anaconda3/envs/__hamronization@1.0.3/lib/python3.10/site-packages/hAMRonization/summarize.py", line 700, in summarize_reports
    raise FileNotFoundError(f"{report} cannot be found")
FileNotFoundError: *.json cannot be found
```

**Comment by bernt-matthias** [comment]
You can simply replace 

```
        *.tsv
        *.json
```
by 

```
        *.{tsv,json}
```

or 

```
        #if $ext == "json"
            *.json
        #else
            *.tsv
        #end if
```

**Comment by bernt-matthias** [comment]
Guess this has been fixed in https://github.com/galaxyproject/tools-iuc/pull/4559
