### ISSUE TITLE
Unicycler: potential problem managing paired collections

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/tools-iuc#4851]
A few users have reported recently problems with the last version of Unicycler. It seems that there's a bug that affect paired collection datasets as input.

Test history: https://usegalaxy.eu/u/gallardoalba/h/unicyclertesthistory

**Comment by gallardoalba** [comment]
Reported error:

`Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 260, in prepare_job
    job_wrapper.prepare()
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1238, in prepare
    ) = tool_evaluator.build()
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 552, in build
    global_tool_logs(self._build_command_line, config_file, "Building Command Line")
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 89, in global_tool_logs
    raise e
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 85, in global_tool_logs
    return func()
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 569, in _build_command_line
    command_line = fill_template(
  File "/opt/galaxy/server/lib/galaxy/util/template.py", line 111, in fill_template
    raise first_exception or e
  File "/opt/galaxy/server/lib/galaxy/util/template.py", line 83, in fill_template
    return unicodify(t, log_exception=False)
  File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1141, in unicodify
    value = str(value)
  File "/opt/galaxy/venv/lib64/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1666188845_2443767_53561.py", line 100, in respond
NameMapper.NotFound: cannot find 'fq1'`

**Comment by wm75** [comment]
@gallardoalba in the failed unicycler run in that test history the inputs are in `fastq.gz` format when the tool only allows `fastqsanger` and `fastqsanger.gz`.
The problem is that the wrapper checks only the cases `is_of_type('fastqsanger')` and `is_of_type('fastqsanger.gz')`, but doesn't set any variables for other cases.

So if you're forcing the tool to work on general fastq data (how does that work btw? can you just drag and drop such datasets into the input boxes?) you're currently out of luck. A possible improvement over this current situation (beyond teaching users to set the correct datatype) would be to change the `is_of_type` checks to more general `.ext.endswith('.gz') ones.
