### ISSUE TITLE
Cleaning up failing regular tests

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#4936]
We got about 200 of those now, which isn't great. For the most part these are bugs in Galaxy or planemo, but let's track this here for now.

- [ ] It seems moving away from nose somehow broke some of the tmpdir assumptions, and tmpdir creation doesn't work for a lot of tools.
- [ ] We're not resolving symlinks anymore: https://github.com/galaxyproject/planemo/pull/1308
- [ ] ?

**Comment by bernt-matthias** [comment]
Thanks for the compilation. For the future we should check planemo  before releases or planemo PR branches against IUC. 

- [ ] make planemo version/source configurable in slash command.

**Comment by bernt-matthias** [comment]
- exception during setting metadata (https://github.com/galaxyproject/tools-iuc/pull/4958): 

```
galaxy.jobs.runners ERROR 2022-11-28 14:54:24,341 [pN:main.1,p:3063045,tN:LocalRunner.work_thread-0] (12/3064188) Job wrapper finish method failed
Traceback (most recent call last):
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 628, in _finish_or_resubmit_job
    job_wrapper.finish(
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1850, in finish
    self._finish_dataset(output_name, dataset, job, context, final_job_state, remote_metadata_directory)
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1668, in _finish_dataset
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/datatypes/goldenpath.py", line 28, in set_meta
    AGPFile(dataset.file_name)
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/datatypes/goldenpath.py", line 137, in __init__
    self._read_file()
  File "/tmp/tmpiyzvjhew/galaxy-dev/lib/galaxy/datatypes/goldenpath.py", line 174, in _read_file
    raise AGPError(self.fname, line_number, "detected more than 9 tab delimited fields")
galaxy.datatypes.goldenpath.AGPError: 

FILE: /tmp/tmpiyzvjhew/files/000/dataset_15.dat
LINE: 1
ERROR: detected more than 9 tab delimited fields
```

**Comment by bernt-matthias** [comment]
This https://github.com/galaxyproject/tools-iuc/pull/4984 might be another case. The tests are successful if executed with planemo 0.74 and fail with 0.75. No idea why .. but at least 0.75 is correct :)

**Comment by bernt-matthias** [comment]
`clair3` fails for the same reason. It tries to get a file `phased_bam.bam` from the workdir which is absent. Then setting metadata fails:

```
setting metadata externally failed for HistoryDatasetAssociation 15: Traceback (most recent call last):
  File "/tmp/tmp1mff07rd/galaxy-dev/lib/galaxy/metadata/set_metadata.py", line 425, in set_metadata_portable
    set_meta(dataset, file_dict)
  File "/tmp/tmp1mff07rd/galaxy-dev/lib/galaxy/metadata/set_metadata.py", line 180, in set_meta
    set_meta_with_tool_provided(
  File "/tmp/tmp1mff07rd/galaxy-dev/lib/galaxy/metadata/set_metadata.py", line 118, in set_meta_with_tool_provided
    dataset_instance.datatype.set_meta(dataset_instance, **set_meta_kwds)
  File "/tmp/tmp1mff07rd/galaxy-dev/lib/galaxy/datatypes/binary.py", line 746, in set_meta
    pysam.index(dataset.file_name, index_file.file_name)
  File "/home/berntm/.planemo/gx_venv_3/lib/python3.9/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "/tmp/tmp1mff07rd/job_working_directory/000/9/outputs/galaxy_dataset_88447f80-d7e1-4ecd-ac6d-91c3586faa20.dat" is in a format that cannot be usefully indexed\n'
```
