### ISSUE TITLE
Install latest metaphlan database using data manager in galaxy

### ISSUE THREAD

**Issue by jamesben114711** [galaxyproject/tools-iuc#4997]
Hello, 
I am new to using galaxy, I hope I can find help with this issue. 
I wanted to install the newest database for metaphlan, but the only one available for download is the old one "**mpa_v30_CHOCOPhlAn_201901**" for metaphlan 

I was trying to modifie the file "data_manager_metaphlan_download.xml"  by replacing the name of the old metaphlan data base 
"**mpa_v30_CHOCOPhlAn_201901**" by the newest database " **mpa_vJan21_CHOCOPhlAnSGB_202103**" 

Under the version, I get  the name of the newest database ( **mpa_vJan21_CHOCOPhlAnSGB_202103** ) 

after I executed the job in galaxy using the tool " **Download and build MetaPhlAn database** (Galaxy Version 3.0.7+galaxy0)"

I got this error : 
================================================================
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_vJan21_CHOCOPhlAnSGB_202103.tar

Warning: Unable to download http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_vJan21_CHOCOPhlAnSGB_202103.tar

Downloading http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_vJan21_CHOCOPhlAnSGB_202103.md5

Warning: Unable to download http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_vJan21_CHOCOPhlAnSGB_202103.md5
File "/home/djamal/Desktop/usegalaxy/galaxy/database/jobs_directory/000/6/working/dataset_86549aae-47ca-4f1d-b596-3e4d07c32e37_files/mpa_vJan21_CHOCOPhlAnSGB_202103/mpa_vJan21_CHOCOPhlAnSGB_202103.md5" not found!
File "/home/djamal/Desktop/usegalaxy/galaxy/database/jobs_directory/000/6/working/dataset_86549aae-47ca-4f1d-b596-3e4d07c32e37_files/mpa_vJan21_CHOCOPhlAnSGB_202103/mpa_vJan21_CHOCOPhlAnSGB_202103.tar" not found!
MD5 checksums not found, something went wrong!
Traceback (most recent call last):
  File "/home/djamal/Desktop/usegalaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan_database_downloader/9c43baa60906/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.py", line 136, in <module>
    download_metaphlan_db(
  File "/home/djamal/Desktop/usegalaxy/galaxy/database/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan_database_downloader/9c43baa60906/data_manager_metaphlan_database_downloader/data_manager/data_manager_metaphlan_download.py", line 101, in download_metaphlan_db
    subprocess.check_call(cmd, shell=True)
  File "/home/djamal/Desktop/usegalaxy/galaxy/database/dependencies/_conda/envs/__metaphlan@3.0.7/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'metaphlan --install --index mpa_vJan21_CHOCOPhlAnSGB_202103 --bowtie2db /home/djamal/Desktop/usegalaxy/galaxy/database/jobs_directory/000/6/working/dataset_86549aae-47ca-4f1d-b596-3e4d07c32e37_files/mpa_vJan21_CHOCOPhlAnSGB_202103' returned non-zero exit status 1.

=====================================================================
What I understand is that the script is trying to download from this link 

http://cmprod1.cibio.unitn.it/biobakery3/metaphlan_databases/mpa_vJan21_CHOCOPhlAnSGB_202103.tar

but the database is in the biobakery4 folder and not the biobakery3 ( when I followed the download link ) 

So could you please help me with this ? Is there any way to get the latest version of the database installed?

I have also tried the tool : [data_manager_metaphlan2_database_downloader but also gives another error. 

P.S: before modifying the "data_manager_metaphlan_download.xml" file, I was able to install the old database mpa_v30_CHOCOPhlAn_201901

Thank you for your help

**Comment by bgruening** [comment]
Indeed we are working on the new DB version. Thanks a lot for reporting!

**Comment by jamesben114711** [comment]
Thank you so much, can't wait for the new update !

**Comment by jamesben114711** [comment]
> Indeed we are working on the new DB version. Thanks a lot for reporting!

Hello Grüning,
Do you have any estimation where the new DB version will available?

Thank you for your time
