### ISSUE TITLE
Mothur: chimera.uchime makes galaxy crash by outputting empty count table

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/tools-iuc#5178]
I am running the latest version (1.39.5) on galaxy 21.09. 
The job seems to run fine, without errors. It is in the output processing when metadata is gathered that the crash occurs:

```
Traceback (most recent call last):
  File "/exports/galaxy/testgalaxy/server/lib/galaxy/jobs/runners/__init__.py", line 547, in _finish_or_resubmit_job
    job_wrapper.finish(tool_stdout, tool_stderr, exit_code, check_output_detected_state=check_output_detected_state, job_stdout=job_stdout, job_stderr=job_stderr)
  File "/exports/galaxy/testgalaxy/server/lib/galaxy/jobs/__init__.py", line 1736, in finish
    output_name, dataset, job, context, final_job_state, remote_metadata_directory
  File "/exports/galaxy/testgalaxy/server/lib/galaxy/jobs/__init__.py", line 1591, in _finish_dataset
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/exports/galaxy/testgalaxy/server/lib/galaxy/datatypes/mothur.py", line 798, in set_meta
    colnames = headers[0]
IndexError: list index out of range
```

I had a look at the data, uchime.accnos and uchime.chimeras are fine. Uchime.count_table is an empty file. I think this causes the above crash, as there is no header to extract the colnames from.

I wonder how to best fix this issue. Can anybody help me?

**Comment by bgruening** [comment]
@rhpvorderman I guess we need to fix the mothur datatypes (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/mothur.py) to be more forgiving.

**Comment by rhpvorderman** [comment]
I had contact with the person whom I testing the pipeline for and he said the table shouldn't be empty in the first place. So I am a bit hesitant to do that. On the other hand, it is a bit annoying if the issue stops a workflow.
I will see if I can fix the issue in the galaxy code.

**Comment by bernt-matthias** [comment]
Fix on the Galaxy side should be easy: 

just add `if dataset.has_data():` around the body of the set_meta function [here](https://github.com/galaxyproject/galaxy/blob/83489c7e067de8fa1d3ed42efcd541f513344166/lib/galaxy/datatypes/mothur.py#L856) .. analogous to other mother data types.. like [here](https://github.com/galaxyproject/galaxy/blob/83489c7e067de8fa1d3ed42efcd541f513344166/lib/galaxy/datatypes/mothur.py#L60)

> the table shouldn't be empty in the first place

of course it would be nice to fix this as well.
