### ISSUE TITLE
Pycoqc : No index found for bam file

### ISSUE THREAD

**Issue by tchaussepiedifb** [galaxyproject/tools-iuc#5195]
Hello
I think I spotted an error with toolshed.g2.bx.psu.edu/repos/iuc/pycoqc/pycoqc/2.5.2+galaxy0
Tool Standard Error:
```
Checking arguments values
Check input data files
Traceback (most recent call last):
  File "/path/to/dependencies/_conda/envs/__pycoqc@2.5.2/bin/pycoQC", line 10, in <module>
    sys.exit(main_pycoQC())
  File "/path/to/dependencies/_conda/envs/__pycoqc@2.5.2/lib/python3.7/site-packages/pycoQC/__main__.py", line 132, in main_pycoQC
    quiet = args.quiet)
  File "/path/to/dependencies/_conda/envs/__pycoqc@2.5.2/lib/python3.7/site-packages/pycoQC/pycoQC.py", line 129, in pycoQC
    quiet=quiet)
  File "/path/to/dependencies/_conda/envs/__pycoqc@2.5.2/lib/python3.7/site-packages/pycoQC/pycoQC_parse.py", line 89, in __init__
    self.bam_file_list = expand_file_names(bam_file, bam_check=True)
  File "/path/to/dependencies/_conda/envs/__pycoqc@2.5.2/lib/python3.7/site-packages/pycoQC/common.py", line 341, in expand_file_names
    raise pycoQCError("No index found for bam file: {}. Please index with samtools index".format(f))
pycoQC.common.pycoQCError: No index found for bam file: /galaxy/my/dataset/path/dataset.dat. Please index with samtools index
```
I think it is looking for a bai in the same place as the bam but not finding it.
There are many tools that make a symbolic link between bam files and their bai files in the working directory but not this one. 
What do you think about this?

**Comment by bernt-matthias** [comment]
Seems reasonable. Do you have a test case including a bam file (<1mb per file )?

**Comment by bernt-matthias** [comment]
Thanks. Do you also have the other inputs and parameter values?

**Comment by tchaussepiedifb** [comment]
Oh sorry, 
there is also the [sequencing_summary.txt](https://github.com/galaxyproject/tools-iuc/files/11030156/sequencing_summary.txt)
and it ran with default parameters
