### ISSUE TITLE
Input size checks in `datamash_transpose` make the tool Pulsar-incompatible

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/tools-iuc#5621]
In #5193, input size checks were added to the `datamash_transpose` tool. These are implemented in Cheetah, and thus `$in_file` in this context is specific to the compute environment, but the template is executed on the Galaxy server. Thus, `$in_file` will be an invalid (remote) path if the selected destination is Pulsar:

```pytb
galaxy.jobs.runners.pulsar ERROR 2023-11-08 13:22:07,410 [pN:main_w4_handler1,p:21105,tN:PulsarJobRunner.work_thread-2] failure running job 53568108
Traceback (most recent call last):
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 491, in __prepare_job
  job_wrapper.prepare(**prepare_kwds)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1254, in prepare
  ) = tool_evaluator.build()
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 568, in build
  global_tool_logs(self._build_command_line, config_file, "Building Command Line")
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 96, in global_tool_logs
  raise e
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 92, in global_tool_logs
  return func()
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 585, in _build_command_line
  command_line = fill_template(
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/template.py", line 143, in fill_template
  raise first_exception or e
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/template.py", line 87, in fill_template
  return unicodify(t, log_exception=False)
File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1153, in unicodify
  value = str(value)
File "/cvmfs/main.galaxyproject.org/venv/lib/python3.8/site-packages/Cheetah/Template.py", line 1053, in __unicode__
  return getattr(self, mainMethName)()
File "cheetah_DynamicallyCompiledCheetahTemplate_1699471327_4082735_11370.py", line 87, in respond
File "/cvmfs/main.galaxyproject.org/deps/_conda/envs/_galaxy_/lib/python3.8/genericpath.py", line 50, in getsize
  return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/jetstream2/scratch/main/jobs/53568108/inputs/dataset_e0451e52-9471-4e32-99b0-769c510a25f8.dat'
```

**Comment by bernt-matthias** [comment]
Out of curiosity how is then `datamash transpose $in_file > $out_file` working? Is the expansion of variables not part of cheetah?

**Comment by natefoo** [comment]
That executes on the compute resource, it's the Cheetah constructs (`#set file_size_MB = os.path.getsize(str($in_file)) / (1024 * 1024)`) that run when the template is interpolated. More specifically, the template values `$in_file` and `$out_file` in your example *are* filled on the Galaxy server, but execution of the filled `datamash transpose /path/to/in.dat > /path/to/out.dat` command does not happen until the job actually runs.

**Comment by natefoo** [comment]
Thanks @mvdbeek!
