### ISSUE TITLE
make pygenometracks error messages more informative for common input problems 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#5631]
Provide more help for naive users when they get an error.

 "cannot unpack non-iterable NoneType object" is too broad for user self-help.

toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.8+galaxy2

Not sure if bad coordinates are the trigger or not. But is required so presumably not empty on submission. Shows up as empty on job details "i" view after the fact. Would also be nice to capture whatever they enter on the form originally, for any use case since this is where we tell them to check when something goes wrong.

![file](https://github.com/galaxyproject/tools-iuc/assets/8999735/023d69fe-8311-4eb4-ae2a-dd35512f1864)

```
INFO:pygenometracks.tracksClass:initialize 1. [bedgraph_matrix_0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/tracks/BedGraphTrack.py", line 191, in load_file
    self.tbx = pysam.TabixFile(self.properties['file'])
  File "pysam/libctabix.pyx", line 350, in pysam.libctabix.TabixFile.__cinit__
  File "pysam/libctabix.pyx", line 382, in pysam.libctabix.TabixFile._open
OSError: index `/corral4/main/objects/0/7/d/dataset_07db3743-a18f-4991-b093-c8535beaaaf3.dat.tbi` not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks([args.tracks.name](http://args.tracks.name/), args.width, fig_height=args.height,
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/tracksClass.py", line 338, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/tracks/BedGraphMatrixTrack.py", line 87, in __init__
    self.load_file()
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/tracks/BedGraphTrack.py", line 194, in load_file
    self.interval_tree, __, __ = file_to_intervaltree(self.properties['file'],
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/utilities.py", line 116, in file_to_intervaltree
    file_to_open = temp_file_from_intersect(file_name, plot_regions, 0)
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/utilities.py", line 70, in temp_file_from_intersect
    plot_regions_ext = [(chrom, max(0, start - around_region), end + around_region) for chrom, start, end in plot_regions]
  File "/usr/local/lib/python3.10/site-packages/pygenometracks/utilities.py", line 70, in <listcomp>
    plot_regions_ext = [(chrom, max(0, start - around_region), end + around_region) for chrom, start, end in plot_regions]
TypeError: cannot unpack non-iterable NoneType object
```

xref https://github.com/galaxyproject/galaxy/issues/3107

**Comment by lldelisle** [comment]
@jennaj do you still have access to the history? If yes could you share it so I can have a look and try to improve the error message?
