### ISSUE TITLE
Error with Scanpy Read10x tool version 1.8.1+galaxy93

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/tools-iuc#5636]
That's the error message when I'm running this step with 1.8.1+galaxy93
![image](https://github.com/galaxyproject/training-material/assets/44121095/f0f4e77a-87dc-4974-9ef2-d27b25b2e7db)

If it's not a quick fix, we might want to hide the latest version

_Originally posted by @wee-snufkin in https://github.com/galaxyproject/training-material/pull/4411#discussion_r1367922079_

**Comment by nomadscientist** [comment]
![Screenshot 2023-11-14 at 17 20 45](https://github.com/galaxyproject/tools-iuc/assets/44605769/d8a3630b-c250-4b06-a319-77a92f915ab2)

**Comment by nomadscientist** [comment]
@pcm32 @bgruening @wee-snufkin

**Comment by nomadscientist** [comment]
Nope, tried it today and it didn't work

**Comment by nomadscientist** [comment]
Nope just tested it, still fails

**Comment by bgruening** [comment]
Can you please send me a new error report? This error above is hopefully solved.

**Comment by nomadscientist** [comment]
`Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/bin/scanpy-read-10x", line 6, in <module>
    from scanpy_scripts.cmds import READ_CMD
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy_scripts/__init__.py", line 15, in <module>
    from . import lib
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy_scripts/lib/__init__.py", line 5, in <module>
    from ._read import read_10x
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy_scripts/lib/_read.py", line 6, in <module>
    import scanpy as sc
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy/__init__.py", line 16, in <module>
    from . import plotting as pl
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.6/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 35, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by nomadscientist** [comment]
https://usegalaxy.eu/u/wendi.bacon/h/unnamed-history-7

**Comment by bgruening** [comment]
Can you please try again? :)

**Comment by pcm32** [comment]
I tried this on our instance which uses singularity and it is working well. Can the tool be switched to use the singularity container on .eu?

**Comment by nomadscientist** [comment]
I suspect there are issues with this entire suite, as I've just tried Scanpy RunFDG and it failed, and this is the same for the latest Manipulate AnnData version 
(Galaxy Version 0.10.3+galaxy0)
Can you send us some of the workflows you have functioning on your instance Pablo so we can test them (and thereby eliminate user error)?
Currently, these tools break all our tutorials if a user accidentally uses them, so it's a concern
