### ISSUE TITLE
Gemini 0.18.1.0 install issue

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/tools-iuc#597]
@bgruening  

When trying to install updated versions of the gemini wrappers I get the following error:

`tool_shed.galaxy_install.install_manager ERROR 2016-02-16 12:54:52,733 Error installing tool dependency gemini version 0.18.1: Unable to locate required tool shed repository named package_gemini_0_18_1 owned by iuc with revision 13ce32ffda3a.
Traceback (most recent call last):
  File "lib/tool_shed/galaxy_install/install_manager.py", line 198, in install_specified_tool_dependencies
    from_tool_migration_manager=from_tool_migration_manager )
  File "lib/tool_shed/galaxy_install/install_manager.py", line 301, in install_package
    tool_dependency_db_records=None )
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 97, in process_tag_set
    tool_dependency_db_records=tool_dependency_db_records )
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 519, in process_tag_set
    from_tool_migration_manager=from_tool_migration_manager )
  File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/tag_handler.py", line 507, in handle_complex_repository_dependency_for_package
    raise Exception( message )
Exception: Unable to locate required tool shed repository named package_gemini_0_18_1 owned by iuc with revision 13ce32ffda3a.`

Installation process stops afterwards.

Thanks!
Matthias

**Comment by matthdsm** [comment]
Ok, apparently this is a non issue
It seems there was an issue with the automatic handling of dependencies, fixed it by manually updating to the correct revision.

Matthias
