### ISSUE TITLE
package_python_2_7_scipy_0_14 fails to install on Test

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#601]
thus rendering the deeptools uninstallable
surprisingly this one installs fine:
https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_scipy_0_14

```
/galaxy/test/deps/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/galaxy/test/deps/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
/galaxy/test/deps/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/system_info.py:1603: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/system_info.py:1612: UserWarning:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  warnings.warn(BlasNotFoundError.__doc__)
/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/system_info.py:1615: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  warnings.warn(BlasSrcNotFoundError.__doc__)
Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    setup_package()
  File "setup.py", line 246, in setup_package
    setup(**metadata)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 173, in configuration
    config.add_subpackage('scipy')
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 12, in configuration
    config.add_subpackage('integrate')
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/integrate/setup.py", line 12, in configuration
    blas_opt = get_info('blas_opt',notfound_action=2)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/system_info.py", line 369, in get_info
    return cl().get_info(notfound_action)
  File "/galaxy/test/deps/numpy/1.9/iuc/package_python_2_7_numpy_1_9/c1e72cd24a9c/lib/python/numpy/distutils/system_info.py", line 527, in get_info
    raise self.notfounderror(self.notfounderror.__doc__)
numpy.distutils.system_info.BlasNotFoundError:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
```

**Comment by bgruening** [comment]
Fixed.
