### ISSUE TITLE
bam_filter Parameter validation failed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#603]
Hi, 

I get with this error with https://github.com/galaxyproject/tools-iuc/blob/master/tools/ngsutils/bam_filter.xml and 16.01.

It seems that all _optional_ integers are throwing this error. Does anyone has an idea?
ping @guerler ... is this some new UI form issue?

==> web2.log <==
galaxy.workflow.run DEBUG 2016-02-17 10:47:36,555 Workflow step 68837 of invocation 11359 invoked (1725.978 ms)
galaxy.tools INFO 2016-02-17 10:47:36,651 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,652 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,653 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,654 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools.execute WARNING 2016-02-17 10:47:36,654 There was a failure executing a job for tool [toolshed.g2.bx.psu.edu/repos/iuc/ngsutils_bam_filter/ngsutils_bam_filter/0.5.7.1] - {'maxlen': "Value no longer valid for 'Remove reads that are larger than', replacing with default", 'maximum_mismatch_ratio': "Value no longer valid for 'Filter by maximum mismatch ratio', replacing with default", 'mismatch': "Value no longer valid for 'Remove reads with that many mismatches', replacing with default", 'minlen': "Value no longer valid for 'Remove reads that are smaller than', replacing with default"}
galaxy.tools INFO 2016-02-17 10:47:36,655 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,656 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,657 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,658 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools.execute WARNING 2016-02-17 10:47:36,658 There was a failure executing a job for tool [toolshed.g2.bx.psu.edu/repos/iuc/ngsutils_bam_filter/ngsutils_bam_filter/0.5.7.1] - {'maxlen': "Value no longer valid for 'Remove reads that are larger than', replacing with default", 'maximum_mismatch_ratio': "Value no longer valid for 'Filter by maximum mismatch ratio', replacing with default", 'mismatch': "Value no longer valid for 'Remove reads with that many mismatches', replacing with default", 'minlen': "Value no longer valid for 'Remove reads that are smaller than', replacing with default"}
galaxy.tools INFO 2016-02-17 10:47:36,659 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,659 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,660 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools INFO 2016-02-17 10:47:36,661 Parameter validation failed.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1731, in check_and_update_param_values_helper
    input.validate( value, history=trans.history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 297, in validate
    return super( TextToolParameter, self ).validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 216, in validate
    validator.validate( value, history )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/parameters/validation.py", line 164, in validate
    if not self.min <= float( value ):
TypeError: float() argument must be a string or a number
galaxy.tools.execute WARNING 2016-02-17 10:47:36,661 There was a failure executing a job for tool [toolshed.g2.bx.psu.edu/repos/iuc/ngsutils_bam_filter/ngsutils_bam_filter/0.5.7.1] - {'maxlen': "Value no longer valid for 'Remove reads that are larger than', replacing with default", 'maximum_mismatch_ratio': "Value no longer valid for 'Filter by maximum mismatch ratio', replacing with default", 'mismatch': "Value no longer valid for 'Remove reads with that many mismatches', replacing with default", 'minlen': "Value no longer valid for 'Remove reads that are smaller than', replacing with default"}
galaxy.tools.execute DEBUG 2016-02-17 10:47:36,661 Executed all jobs for tool request: (64.667 ms)
galaxy.workflow.run ERROR 2016-02-17 10:47:36,672 Failed to schedule Workflow[id=4495,name=WIP dev FLASH_full_hisat2_hg19_v1.2 MINIMAL], problem occurred on WorkflowStep[index=3,type=tool].
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/modules.py", line 1188, in execute
    raise Exception(message)
Exception: Failed to create 3 out of 3 job(s) for workflow step.
galaxy.workflow.run ERROR 2016-02-17 10:47:36,673 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/modules.py", line 1188, in execute
    raise Exception(message)
Exception: Failed to create 3 out of 3 job(s) for workflow step.
10.126.47.109 - - [17/Feb/2016:10:47:33 +0200] "POST /workflow/run?id=288daeaa7c29ea3b HTTP/1.1" 500 - "http://galaxy.uni-freiburg.de/workflow/run?id=288daeaa7c29ea3b" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
Error - <type 'exceptions.Exception'>: Failed to create 3 out of 3 job(s) for workflow step.
URL: http://galaxy.uni-freiburg.de/workflow/run?id=288daeaa7c29ea3b
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/galaxy/galaxy-dist/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/usr/local/galaxy/galaxy-dist/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/web/framework/base.py', line 184 in handle_request
  body = method( trans, **kwargs )
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 1131 in run
  workflow_run_config=run_config
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py', line 22 in invoke
  return __invoke( trans, workflow, workflow_run_config, workflow_invocation, populate_state )
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py', line 82 in __invoke
  outputs = invoker.invoke()
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py', line 162 in invoke
  jobs = self._invoke_step( step )
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/run.py', line 228 in _invoke_step
  jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
File '/usr/local/galaxy/galaxy-dist/lib/galaxy/workflow/modules.py', line 1188 in execute
  raise Exception(message)
Exception: Failed to create 3 out of 3 job(s) for workflow step.

CGI Variables
-------------
  CONTENT_LENGTH: '5025'
  CONTENT_TYPE: 'application/x-www-form-urlencoded'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.8,de;q=0.6'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'Keep-Alive'
  HTTP_COOKIE: 'galaxysession=c6ca0ddb55be603a1ecf63eeb7b03213c1926a73be74f9809002ef1f700b77d19cd6b25600cd1ced; _gat=1; _ga=GA1.2.473792004.1455102609'
  HTTP_DNT: '1'
  HTTP_HOST: 'galaxy.uni-freiburg.de'
  HTTP_ORIGIN: 'http://galaxy.uni-freiburg.de'
  HTTP_REFERER: 'http://galaxy.uni-freiburg.de/workflow/run?id=288daeaa7c29ea3b'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36'
  HTTP_X_FORWARDED_FOR: '10.126.47.109'
  HTTP_X_FORWARDED_HOST: 'galaxy.uni-freiburg.de'
  HTTP_X_FORWARDED_SERVER: 'galaxy.bi.uni-freiburg.de'
  ORGINAL_HTTP_HOST: 'localhost:8082'
  ORGINAL_REMOTE_ADDR: '127.0.0.1'
  PATH_INFO: '/workflow/run'
  QUERY_STRING: 'id=288daeaa7c29ea3b'
  REMOTE_ADDR: '10.126.47.109'
  REQUEST_METHOD: 'POST'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '8082'
  SERVER_PROTOCOL: 'HTTP/1.1'

WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x1edad350>
  is_api_request: False
  paste.cookies: (<SimpleCookie: _ga='GA1.2.473792004.1455102609' _gat='1' galaxysession='c6ca0ddb55be603a1ecf63eeb7b03213c1926a73be74f9809002ef1f700b77d19cd6b25600cd1ced'>, 'galaxysession=c6ca0ddb55be603a1ecf63eeb7b03213c1926a73be74f9809002ef1f700b77d19cd6b25600cd1ced; _gat=1; _ga=GA1.2.473792004.1455102609')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x1edad2d0>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x21efb090>
  paste.parsed_querystring: ([('id', '288daeaa7c29ea3b')], 'id=288daeaa7c29ea3b')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '77ad3a6ad55b11e5a1db984be1655608'
  webob._body_file: (<_io.BufferedReader>, <socket._fileobject object at 0x23e2f750 length=5025>)
  webob._parsed_post_vars: (MultiDict([('68839|tool_state', u'315fa6545bb7d71723c602d1ada78da548d5e94f:7b22696e707574223a20226e756c6c222c20225f5f726572756e5f72656d61705f6a6f625f69645f5f223a206e756c6c2c20225f5f706167655f5f223a20307d'), ('68839|multi_mode', u'matched'), ('68839|input', u'8793'), ('__switch_default__', u'select_single_collection'), ('68839|__force_update__input', u'true'), ('68838|tool_state', u'd4f660a9d19581778aca5cf7d8cc857d58bf2f75:7b22616c69676e6d656e745f6f7074696f6e73223a20227b5c22616c69676e6d656e745f6f7074696f6e735f73656c6563746f725c223a205c2264656661756c74735c222c205c225f5f63757272656e745f636173655f5f5c223a20307d222c2022696e7075745f666f726d6174223a20227b5c227061697265645c223a207b5c2272656164735c223a206e756c6c2c205c227061697265645f656e645f6f7074696f6e735c223a207b5c227061697265645f656e645f6f7074696f6e735f73656c6563746f725c223a205c2264656661756c74735c222c205c225f5f63757272656e745f636173655f5f5c223a20307d2c205c227061697265645f73656c6563746f725c223a205c227061697265645f636f6c6...t at 0x1e843e30>)
  webob._parsed_query_vars: (GET([(u'id', u'288daeaa7c29ea3b')]), 'id=288daeaa7c29ea3b')
  webob.is_body_seekable: True
  wsgi process: 'Multithreaded'

**Comment by nsoranzo** [comment]
May be related to galaxyproject/galaxy#1721.

**Comment by bgruening** [comment]
Thanks @nsoranzo

**Comment by guerler** [comment]
Can you test this fix: https://github.com/galaxyproject/galaxy/compare/release_16.01...guerler:fix_check_and_update_release_000?expand=1

**Comment by bgruening** [comment]
@guerler seems to work! i would +1 this PR :)

**Comment by bgruening** [comment]
@jmchilton what do you think about this one? It was added in https://github.com/guerler/galaxy/commit/886f6d2d707a9b4e2a80b0aaa89157e1137415ad

**Comment by guerler** [comment]
The issue here is that the check performed transforms the value into a string and back before validation. This is inconsistent and leads to undesired consequences. In #1764 the validation call has been modified to use the regular check_param caller (see: https://github.com/galaxyproject/galaxy/pull/1764/files#diff-1bef786a2b2ea704c1748e41cd25dd33R1251). I also suggest to remove the validation in the execute caller since a validation error leads to an ungraceful fail as we can see above. It also breaks the job resubmission and workflow pausing feature. I think that a new validation point at an earlier stage could be reasonable, if so I will introduce it for 16.04.

**Comment by bgruening** [comment]
I think this was fixed by @guerler. If not I will reopen.
