### ISSUE TITLE
Constrain biopython dependency for deg_annotate

### ISSUE THREAD

**Issue by lmfaber** [galaxyproject/tools-iuc#6301]
Hi there,

I found and I found an issue with the tool [Annotate DESeq2/DEXSeq output tables](https://toolshed.g2.bx.psu.edu/repository?repository_id=e33c4ee81be2b1b4).

We're running a self-hosted Galaxy instance (24.1.1) on a Ubuntu system (22.04.4) using conda (24.7.1) for job execution. Galaxy creates a conda environment for this tool and I believe what's happening is with a newer Python version (3.12), biopython is updated to a version deg_annotate can't handle.

The conda environment list is as follows:
```
conda list 
# packages in environment at /srv/galaxy/var/dependencies/_conda/envs/mulled-v1-61ba501081daf9921383c1402c51e68d5421ca2253eaf7867e6d4de3e09b2263:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bcbiogff                  0.6.4                      py_1    bioconda
bedtools                  2.27.0               he513fc3_4    bioconda
biopython                 1.83            py312h98912ed_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_1    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.26.4          py312heda63a1_0    conda-forge
openssl                   3.3.0                h4ab18f5_3    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.12.3          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
```

The resulting error of the jobs are:
```
Traceback (most recent call last):
  File "/srv/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/deg_annotate/e98d4ab5b5bc/deg_annotate/deg_annotate.py", line 5, in <module>
    from BCBio import GFF
  File "/srv/galaxy/var/dependencies/_conda/envs/mulled-v1-61ba501081daf9921383c1402c51e68d5421ca2253eaf7867e6d4de3e09b2263/lib/python3.12/site-packages/bcbio_gff-0.6.4-py2.7.egg/BCBio/GFF/__init__.py", line 3, in <module>
  File "/srv/galaxy/var/dependencies/_conda/envs/mulled-v1-61ba501081daf9921383c1402c51e68d5421ca2253eaf7867e6d4de3e09b2263/lib/python3.12/site-packages/bcbio_gff-0.6.4-py2.7.egg/BCBio/GFF/GFFParser.py", line 32, in <module>
ImportError: cannot import name 'UnknownSeq' from 'Bio.Seq' (/srv/galaxy/var/dependencies/_conda/envs/mulled-v1-61ba501081daf9921383c1402c51e68d5421ca2253eaf7867e6d4de3e09b2263/lib/python3.12/site-packages/Bio/Seq.py)
```

Checking the [changelog of biopython](https://github.com/biopython/biopython/blob/master/NEWS.rst#3-june-2021-biopython-179), I can see that 'UnknownSeq' has been deprecated. So what I did to fix this, is to pin the biopython version to 1.78 in the according conda environment.

The permanent and future proof fix would be to pin biopython to said version. Change

https://github.com/galaxyproject/tools-iuc/blob/731f04b7f59bd92cc68ad1c7565ae35960e75645/tools/deg_annotate/deg_annotate.xml#L3-L6

to this:

```
 <requirements> 
     <requirement type="package" version="2.27.0">bedtools</requirement> 
     <requirement type="package" version="0.6.4">bcbiogff</requirement> 
     <requirement type="package" version="1.78">biopython</requirement> 
 </requirements> 
```

Keep up the good work!

**Comment by bgruening** [comment]
Thanks for the detailed analysis. Can you maybe open a PR for the bcbiogff recipe in bioconda and pin the biopthon version there. This will fix it for all users of this package not just Galaxy users.

**Comment by lmfaber** [comment]
Great idea! I have opened a [PR](https://github.com/bioconda/bioconda-recipes/pull/50491) in the bioconda-recipes repository.

**Comment by bgruening** [comment]
Given the new conda package, I hope this issue is resolved now. Thanks ks a lot for fixing it @lmfaber.
