### ISSUE TITLE
RAxML issue

### ISSUE THREAD

**Issue by Hymenium** [galaxyproject/tools-iuc#6447]
I am getting an error from the raxml.py code if I try to use the 'estimate individual per-parition branch length (-M)' in RAxML. 

It seems like these partition files are not found to calculate the final branch lengths, and the branch lengths produced do not make sense. Not using this -M option requires unrealistic assumptions.

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/raxml/b1e68bbe4cef/raxml/raxml.py", line 90, in <module>
    __main__()
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/raxml/b1e68bbe4cef/raxml/raxml.py", line 62, in __main__
    files.sort(key=getint)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

It seems to be related to getting the files to sort in this line:

https://github.com/galaxyproject/tools-iuc/blob/07701847a3c4d66ee12cecd37b5129ed6984082a/tools/raxml/raxml.py#L77

**Comment by bernt-matthias** [comment]
Sorry for the late reply. Any chance to share the case you are computing here?
