### ISSUE TITLE
Bug: package_atlas_3_10 fails to compile during install

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-iuc#815]
When I attempt to install the latest [trinity package](https://toolshed.g2.bx.psu.edu/view/iuc/trinity/f7564c3f9dc0) (revision 6:f7564c3f9dc0) from the main toolshed, I've run into an error with the atlas dependency. `package_atlas_3_10` installs, missing the `atlas` dependency due to an error during installation: 

    mkdir: cannot create directory `ATLAS/build': No such file or directory

This is using `release_16.04` of Galaxy, on CentOS 6.

EDITED: Changed name to clarify, this issue is to reference the problems during install when compiling. Opened issue #831 to track issues during install from precompiled linux_x64 package.

**Comment by abretaud** [comment]
Thanks for being the trinity beta tester!
Are you installing on a 64 or 32 bit version of centos?
Looking at the atlas package, on a x64 linux it should install precompiled binaries
Anyway, I think it should be fixed with #814

**Comment by lparsons** [comment]
@abretaud You're welcome!
I'm installing on 64bit CentOS 6.

**Comment by lparsons** [comment]
@abretaud I'm testing the fix now, however, looking at the logs more carefully, you are correct. It is attempting to install the precompiled version, but aparently another bug is preventing that and causing it to fall back to compiling...

```
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2016-06-16 16:34:50,023 Attempting to download via url: https://depot.galaxyproject.org/software/atlas/atlas_3.10.2_linux_x64.tar.gz
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2016-06-16 16:35:11,984 Successfully downloaded from url: https://depot.galaxyproject.org/software/atlas/atlas_3.10.2_linux_x64.tar.gz
tool_shed.galaxy_install.tool_dependencies.recipe.install_environment:atlas DEBUG 2016-06-16 16:35:11,991 +
                        command -v gfortran || return 0
                        BUNDLED_LGF_CANON=/opt/galaxy/galaxy-app/tool-dependencies/atlas/3.10.2/iuc/package_atlas_3_10/f27d2f8761ae/lib/libgfortran.so.3.0.0 &&
                        BUNDLED_LGF_VERS=`objdump -p $BUNDLED_LGF_CANON | grep GFORTRAN_1 | sed -r 's/.*GFORTRAN_1\.([0-9])+/\1/' | sort -n | tail -1` &&
                        echo 'program test; end program test' > test.f90 &&
                        gfortran -o test test.f90 &&
                        LGF=`ldd test | grep libgfortran | awk '{print $3}'` &&
                        LGF_CANON=`readlink -f $LGF` &&
                        LGF_VERS=`objdump -p $LGF_CANON | grep GFORTRAN_1 | sed -r 's/.*GFORTRAN_1\.([0-9])+/\1/' | sort -n | tail -1` &&
                        if [ $LGF_VERS -gt $BUNDLED_LGF_VERS ]; then
                            cp -p $BUNDLED_LGF_CANON ${BUNDLED_LGF_CANON}.bundled &&
                            cp -p $LGF_CANON $BUNDLED_LGF_CANON
                        fi

tool_shed.galaxy_install.install_manager ERROR 2016-06-16 16:35:12,036 Error installing tool dependency atlas version 3.10.2.
Traceback (most recent call last):
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 124, in install_and_build_package_via_fabric
    tool_dependency = self.install_and_build_package( install_environment, tool_dependency, actions_dict )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 109, in install_and_build_package
    initial_download=False )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 31, in execute_step
    initial_download=initial_download )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 1869, in execute_step
    job_name=package_name )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 117, in handle_command
    output = self.handle_complex_command( command, job_name=job_name )
  File "/opt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 169, in handle_complex_command
    cwd=state.env[ 'lcwd' ] )
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtd66Ymtq'
```

Let me know if you'd prefer this as a separate issue or just part of this one.

**Comment by lparsons** [comment]
@abretaud And to complicate things, the compilation now runs into another error:

    /bin/sh: line 3: /host/static_full_blas_lapack.diff: No such file or directory

**Comment by nsoranzo** [comment]
I wonder how that ever worked! Ping @natefoo

**Comment by lparsons** [comment]
Thanks @abretaud and @nsoranzo, progress is being made... 

Still have the same issue with the compiled package, and now have a new error with atlas compilation: https://gist.github.com/lparsons/abcd043deca5fe0f59fe34cf7554cacc

**Comment by lparsons** [comment]
Looking through the logs, I see this (possibly more helpful) error that isn't in the installation.log file...

```
tool_shed.galaxy_install.tool_dependencies.recipe.install_environment:atlas DEBUG 2016-06-20 19:35:46,662 make[2]: Leaving directory `/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtdW2em14/ATLAS/build'
tool_shed.galaxy_install.tool_dependencies.recipe.install_environment:atlas DEBUG 2016-06-20 19:35:46,662 make[1]: Leaving directory `/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtdW2em14/ATLAS/build'
tool_shed.galaxy_install.tool_dependencies.recipe.install_environment:atlas DEBUG 2016-06-20 19:35:46,663 Cannot find '/opt/galaxy/galaxy-app/database/tmp/tmp-toolshed-mtdW2em14/ATLAS/build/../../lapack-3.5.0.tgz'
```
