### ISSUE TITLE
package_python_2_7_bx_python_0_7 fails to install

### ISSUE THREAD

**Issue by tjansse5** [galaxyproject/tools-iuc#822]
When trying to install package_python_2_7_bx_python_0_7, it fails while attempting to install bx-python 0.7.2 throwing the following error:

`Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    use_setuptools()
  File "[...]/galaxy/database/tmp/tmp-toolshed-mtdRCcwC_/bx-python-0.7.2/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "[...]/galaxy/database/tmp/tmp-toolshed-mtdRCcwC_/bx-python-0.7.2/distribute_setup.py", line 131, in _do_download
    to_dir, download_delay)
  File "[...]/galaxy/database/tmp/tmp-toolshed-mtdRCcwC_/bx-python-0.7.2/distribute_setup.py", line 201, in download_setuptools
    src = urlopen(url)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "[...]/tool_dependencies/python/2.7.10/iuc/package_python_2_7_10/0339c4a9b87b/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>`

I'm running Galaxy 16.04 on Scientific Linux 7.1

**Comment by yhoogstrate** [comment]
@tjansse5 To me it looks like the pypi server was redirecting a http to a https url and urllib2 couldn't deal with it. Do you still have this error?

If so, which version of python are you running? (`python --version`) and could you tell me the path and version of your urllib2 and what happens if you try downloading the file manually:
```
$ python
>>> import urrlib2
>>> urllib2
... <path>
>>> urllib2.__version__
>>> resp = urllib2.urlopen("http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz")
>>> data = resp.read()
>>> len(data)
>>>
>>> resps = urllib2.urlopen("https://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz")
>>> data2 = resps.read()
>>> len(data2)
>>>
>>> data == data2
```

In case you get any error in those above, please also run:
```
respx = urllib2.urlopen("https://github.com/")
data3 = respx.read()
len(data3)
```

**Comment by tjansse5** [comment]
@yhoogstrate Thanks for your reply.
Yes I still have this error. With my standard python installation I have no problems downloading the file. It's only when I'm using the version from iuc's package_python_2_7_10 that this error occurs. I guess that it gets compiled without ssl support. But as it is a dependency for package_python_2_7_bx_python_0_7 the installation fails. Maybe the python package should be fixed so that it supports ssl.
