### ISSUE TITLE
shuffleBed - failure preparing job when selecting an additional BED file 

### ISSUE THREAD

**Issue by pajanne** [galaxyproject/tools-iuc#910]
https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/shuffleBed.xml returns this error message when selecting an additional BED file

```
Traceback (most recent call last):
  File "/data/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 163, in prepare_job
    job_wrapper.prepare()
  File "/data/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 859, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/data/galaxy/galaxy-dist/lib/galaxy/tools/evaluation.py", line 422, in build
    raise e
NotFound: cannot find 'add_bed_select'
```
Only works when no additional BED file is selected.
Galaxy Tool ID:	toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_shufflebed/2.24.0

There may be a problem in the xml wrapper file with the conditional parameter `add_bed`.
Any help would be great, many thanks.

**Comment by pajanne** [comment]
Different error when running the same tool on usegalaxy.org with the same data files. Here is the link to the history in case it may be useful https://usegalaxy.org/u/annepajon/h/testing-shufflebed.

**Comment by nsoranzo** [comment]
@pajanne I think the first error was fixed in #634, can you check you have the latest release installed?

**Comment by nsoranzo** [comment]
The second error is caused by the fact that usegalaxy is not using v2.24.0 of bedtools, but v2.16.1. @martenson any progress on #838 and #895 ?

**Comment by pajanne** [comment]
Checking the xml file installed locally and it does look the same as the latest version...

```
$ cat shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/bedtools/f8b7dc21b4ee/bedtools/shuffleBed.xml 
<tool id="bedtools_shufflebed" name="ShuffleBed" version="@WRAPPER_VERSION@.0">
    <description>randomly redistrubute intervals in a genome</description>
    <macros>
        <import>macros.xml</import>
    </macros>
    <expand macro="requirements" />
    <expand macro="stdio" />
    <command>
<![CDATA[
        bedtools shuffle
        -g $genome
        -i $inputA
        $bedpe
        #if str($seed.seed_choose) == "True":
            -seed $seed.seed
        #end if
        #if str($add_bed.add_bed_select) == "not_be":
            -excl $add_bed_select.excl
            -f $add_bed_select.overlap
        #elif str($add_bed.add_bed_select) == "be":
            -incl $add_bed_select.incl
        #end if
        $chrom
        $chromfirst
        $no_overlap
        $allow_beyond
        -maxTries $maxtries
        > $output
]]>
    </command>
    <inputs>
        <param format="bed,vcf,gff,gff3" name="inputA" type="data" label="BED/VCF/GFF file"/>
        <param name="bedpe" type="boolean" label="The file is in BEDPE format" selected="False" truevalue="-bedpe" falsevalue="" />
        <expand macro="genome" />
        <param name="chrom" type="boolean" selected="False" truevalue="-chrom" falsevalue=""
            label="Keep features in the input file on the same chromosome"
            help="Solely permute their location on the chromosome. By default, both the chromosome and position are randomly chosen. (-chrom)" />
        <expand macro="seed" />
        <conditional name="add_bed">
            <param name="add_bed_select" type="select" label="Choose an additional BED file">
                <option value="no" selected="True">No additional BED file</option>
                <option value="not_be">Coordinates in which features from -i should not be placed?</option>
                <option value="be">coordinates in which features from -i should be placed?</option>
            </param>
            <when value="no" />
            <when value="not_be">
                <param name="excl" type="data" format="bed" label="Choose File" />
                <expand macro="overlap" />
            </when>
            <when value="be">
                <param name="incl" type="data" format="bed" label="Choose File" />
            </when>
        </conditional>
        <param name="chromfirst" type="boolean" selected="False" truevalue="-chromFirst" falsevalue="" 
            label="Choose chromosome first"
            help="Instead of choosing a position randomly among the entire genome (the default), first choose a chrom randomly, and then choose a random start coordinate on that chrom. This leads to features being ~uniformly distributed among the chroms, as opposed to features being distribute as a function of chrom size. (-chromFirst)" />
        <param name="maxtries" type="integer" value="1000"
            label="Max. number of attempts to find a home for a shuffled interval in the presence of -incl or -excl" help="(-maxTries)" />
        <param name="no_overlap" type="boolean" selected="False" truevalue="-noOverlapping" falsevalue=""
            label="Don’t allow shuffled intervals to overlap" help="(-noOverlapping)" />
        <param name="allow_beyond" type="boolean" selected="False" truevalue="-allowBeyondChromEnd" falsevalue=""
            label="Allow the original the length of the original records to extebd beyond the length of the chromosome" help="(-allowBeyondChromEnd)" />
    </inputs>
    <outputs>
        <data format="bed" name="output" />
    </outputs>
    <tests>
        <test>
            <param name="inputA" value="shuffleBed1.bed" ftype="bed" />
            <param name="genome" value="shuffleBed.len" ftype="tabular" />
            <param name="chrom" value="" />
            <param name="seed_choose" value="True" />
            <param name="seed" value="1" />
            <output name="output" file="shuffleBed_result1.bed" ftype="bed" />
        </test>
        <test>
            <param name="inputA" value="shuffleBed1.bed" ftype="bed" />
            <param name="genome" value="shuffleBed.len" ftype="tabular" />
            <param name="chrom" value="True" />
            <param name="seed_choose" value="True" />
            <param name="seed" value="1" />
            <output name="output" file="shuffleBed_result2.bed" ftype="bed" />
        </test>
        <test>
            <param name="inputA" value="shuffleBed1.bed" ftype="bed" />
            <param name="genome" value="shuffleBed.len" ftype="tabular" />
            <param name="excl" value="shuffleBed2.bed" ftype="bed" />
            <param name="seed_choose" value="True" />
            <param name="seed" value="1" />
            <output name="output" file="shuffleBed_result3.bed" ftype="bed" />
        </test>
        <test>
            <param name="inputA" value="shuffleBed1.bed" ftype="bed" />
            <param name="genome" value="shuffleBed.len" ftype="bed" />
            <param name="allow_beyond" value="True" />
            <param name="seed_choose" value="True" />
            <param name="seed" value="1" />
            <output name="output" file="shuffleBed_result4.bed" ftype="bed" />
        </test>
    </tests>
    <help>
<![CDATA[
**What it does**

bedtools shuffle will randomly permute the genomic locations of a feature file among a genome defined in a genome file. One can also provide an “exclusions” BED/GFF/VCF file that lists regions where you do not want the permuted features to be placed. For example, one might want to prevent features from being placed in known genome gaps. shuffle is useful as a null basis against which to test the significance of associations of one feature with another.

.. image:: $PATH_TO_IMAGES/shuffle-glyph.png

@REFERENCES@
]]>
    </help>
    <expand macro="citations" />
</tool>
```

**Comment by pajanne** [comment]
Thanks @nsoranzo for your answers. I was just trying to replicate my issue on usegalaxy.org to show you the issue I'm having. 
I do think I have the latest version installed, thanks for pointing out at the #634 fix.

**Comment by pajanne** [comment]
Oops no I'm blind... sorry @nsoranzo... how can I update? Via the toolshed? I did not see any update for this tool.

**Comment by nsoranzo** [comment]
@pajanne: "Admin" -> "Manage installed tools", click on the small arrow near "bedtools" and select "Update tool shed status". The icon should change from a green tick to yellow or red to indicate that a minor or major update is available. You can then update or install the new version.

**Comment by pajanne** [comment]
Many thanks @nsoranzo I did not see the update because I forgot to click on "Update tool shed status"! My mistake, thanks again. All working fine now. Sorry for taking up your time.
