### ISSUE TITLE
Bowtie2 Data_Manager Issue

### ISSUE THREAD

**Issue by jsarro13** [galaxyproject/tools-iuc#922]
I am indexing reference genomes for bowtie2/tophat2, using the corresponding data manager.  I am getting some successful indexes and others are giving an error.  For the successful ones I see the genomes are appearing in the "built in index" drop down for both bowtie2 and tophat2.  For the unsuccessful ones I am seeing them in the bowtie2 drop down but not tophat2.  Any ideas on what could be causing this issue?

The error message is as follows

Thanks in advance.

```
Traceback (most recent call last):
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/jobs/runners/local.py", line 128, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1375, in finish
    self.tool.exec_after_process( self.queue.app, inp_data, out_data, param_dict, job=job )
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 2107, in exec_after_process
    data_manager.process_result( out_data )
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/tools/data_manager/manager.py", line 303, in process_result
    self.process_move( data_table_name, name, output_ref_values[ name ].extra_files_path, **data_table_value )
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1891, in extra_files_path
    return self.dataset.extra_files_path
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/model/__init__.py", line 1707, in get_extra_files_path
    return self.object_store.get_filename( self, dir_only=True, extra_dir=self._extra_files_path or "dataset_%d_files" % self.id )
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 487, in get_filename
    return self._call_method('get_filename', obj, ObjectNotFound, True, **kwargs)
  File "/vectorbase/web/Galaxy/galaxy-dist/lib/galaxy/objectstore/__init__.py", line 508, in _call_method
    % ( method, str( obj ), str( kwargs ) ) )
ObjectNotFound: objectstore, _call_method failed: get_filename on <galaxy.model.Dataset object at 0x7f2584803590>, kwargs: {'dir_only': True, 'extra_dir': 'dataset_19568_files'}
Tool execution generated the following error message:
Unable to finish job
```

**Comment by nsoranzo** [comment]
Looks more like a Galaxy bug, and stale at this point. Sorry for the lack of earlier response.
