### ISSUE TITLE
TravisCI failing with: unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#961]
e.g.  https://travis-ci.org/peterjc/tools-iuc/jobs/162194742

```
0.39s$ planemo --version
planemo, version 0.32.0
install.7
0.13s$ conda --version
conda 3.19.3
install.8
0.00s$ echo $TRAVIS_COMMIT_RANGE
2509d94fefaf...61cb0505a6e2
4.66s$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range $TRAVIS_COMMIT_RANGE \
                        --chunk_count 4 --chunk ${CHUNK} \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '2509d94fefaf...61cb0505a6e2'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 25, in cli
    paths = filter_paths(ctx, raw_paths, path_type="dir", **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/ci.py", line 24, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/git.py", line 27, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/io.py", line 37, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '2509d94fefaf...61cb0505a6e2' - (, fatal: ambiguous argument '2509d94fefaf...61cb0505a6e2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
)
The command "planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range $TRAVIS_COMMIT_RANGE \
                        --chunk_count 4 --chunk ${CHUNK} \
                        --output changed_repositories_chunk.list
  " failed and exited with 1 during .
Your build has been stopped.
```

This was from commit https://github.com/peterjc/tools-iuc/commit/61cb0505a6e2abc6b87c17fe0a4f456815e97568 on a rebased branch being used to test issue #2941.

Might the git rebasing have confused the TravisCI setup?

**Comment by nsoranzo** [comment]
I don't think this belongs in tools-iuc, but in planemo issue tracker.
A possible fix may be:
```
diff --git a/planemo/git.py b/planemo/git.py
index 1db6b08..e0d2142 100644
--- a/planemo/git.py
+++ b/planemo/git.py
@@ -21,7 +21,7 @@ def command_clone(ctx, src, dest, bare=False, branch=None):
 
 
 def diff(ctx, directory, range):
-    cmd_template = "cd '%s' && git diff --name-only '%s'"
+    cmd_template = "cd '%s' && git diff --name-only '%s' --"
     cmd = cmd_template % (directory, range)
     stdout, _ = io.communicate(
         cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
```

Ping @jmchilton.

**Comment by jmchilton** [comment]
It is definitely a good enhancement. The old method https://github.com/galaxyproject/tools-iuc/pull/927/files did not do this though so I wonder if that is the problem. Was this the latest rebase or did you rebase and push again after the test had started?

**Comment by peterjc** [comment]
I did the following,

1. made branch, one commit, pushed, waited for TravisCI (test passed as expected)
2. one commit intended to break the build, pushed, waited for TravisCI (test still passed as tool was blacklisted)
3. a day later: rebased to have tool whitelisted, force pushed, waited for TravisCI (failed with git issue).

I'm happy to move this issue to planemo - I wasn't sure if the problem was specific to the tools-iuc TravisCI setup or not.

**Comment by peterjc** [comment]
Change recommend by @nsoranzo  applied to planemo by @jmchilton  in https://github.com/galaxyproject/planemo/commit/6f91719619ee0c6e52f5a3fc16bb6368b4eda5b6 - this will be in planemo 0.33.0 at which point I can test it by repeating this TravisCI job (assuming no more rebases or additions to the branch in the meantime).

**Comment by jmchilton** [comment]
This repo pins the planemo version so I think you'd need to update .travis.yml. If we do update .travis.yml we need to skip XSD checking until #939 is resolved.

**Comment by nsoranzo** [comment]
@jmchilton No, tools-iuc is not pinning planemo version since May (commit 03e371510808d84d461326a867503e7db049de9e), we are using the latest version from PyPi. So shed_lint is running with the new xsd tool validation, but linting problems don't make a build fail (not sure this is on purpose, @bgruening?)

**Comment by bgruening** [comment]
It was back in the beginning, but we should enable it I think - it should fail if XSD reports problems. I hope that we can also improve the XSD in this way.

**Comment by peterjc** [comment]
I will try re-running the above failing TravisCI test...

**Comment by peterjc** [comment]
Progress, still fails but with a better error message?  ``bad revision '2509d94fefaf...61cb0505a6e2'``

https://travis-ci.org/peterjc/tools-iuc/jobs/162194742 (second run) for https://github.com/peterjc/tools-iuc/commit/61cb0505a6e2abc6b87c17fe0a4f456815e97568 which was run on TravisCI under ``peterjc/tools-iuc``

```
0.39s$ planemo --version
planemo, version 0.33.0
install.7
0.14s$ conda --version
conda 3.19.3
install.8
0.00s$ echo $TRAVIS_COMMIT_RANGE
2509d94fefaf...61cb0505a6e2
6.37s$ planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range $TRAVIS_COMMIT_RANGE \
                        --chunk_count 4 --chunk ${CHUNK} \
                        --output changed_repositories_chunk.list
  
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '2509d94fefaf...61cb0505a6e2' --
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 25, in cli
    paths = filter_paths(ctx, raw_paths, path_type="dir", **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/ci.py", line 24, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/git.py", line 53, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/io.py", line 43, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '2509d94fefaf...61cb0505a6e2' -- - (, fatal: bad revision '2509d94fefaf...61cb0505a6e2'
)
The command "planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range $TRAVIS_COMMIT_RANGE \
                        --chunk_count 4 --chunk ${CHUNK} \
                        --output changed_repositories_chunk.list
  " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by peterjc** [comment]
Another example following a force-push to update a branch being used for a pull request, commit: https://github.com/galaxyproject/tools-iuc/pull/964/commits/6644b9823587986178f0d884df3c07c56a18189f aka https://github.com/peterjc/tools-iuc/commit/6644b9823587986178f0d884df3c07c56a18189f

Works for the pull request test: https://travis-ci.org/galaxyproject/tools-iuc/builds/163115376 using https://github.com/galaxyproject/tools-iuc/commit/7c37d9a5d2d0de8ce79d3e8032804e7010638c5b which was "Merge 6644b98 into 643293a"

However it fails for me (using TravisCI directly on my forked repo branch): https://travis-ci.org/peterjc/tools-iuc/jobs/163115366

```
cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '82fae55db542...6644b9823587' --
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_ci_find_repos.py", line 25, in cli
    paths = filter_paths(ctx, raw_paths, path_type="dir", **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/ci.py", line 24, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/git.py", line 53, in diff
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/io.py", line 43, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/travis/build/peterjc/tools-iuc' && git diff --name-only '82fae55db542...6644b9823587' -- - (, fatal: bad revision '82fae55db542...6644b9823587'
)
The command "planemo ci_find_repos --exclude_from .tt_blacklist \
                        --exclude packages --exclude data_managers \
                        --changed_in_commit_range "$TRAVIS_COMMIT_RANGE" \
                        --chunk_count 4 --chunk "${CHUNK}" \
                        --output changed_repositories_chunk.list
  " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by nsoranzo** [comment]
@peterjc I've also run in the same issue on https://github.com/TGAC/earlham-galaxytools , I found out that this is due to `$TRAVIS_COMMIT_RANGE` being wrong when force pushing in a branch, see https://github.com/travis-ci/travis-ci/issues/2668. If you due a PR from this brach to master, the tests will pass.

**Comment by peterjc** [comment]
Good detective work @nsoranzo, yes as per https://github.com/travis-ci/travis-ci/issues/2668 the problem is that ``$TRAVIS_COMMIT_RANGE`` is meaningless after a force push (and this is not something TravisCI can do much about).

I'm reopening this issue as ``tools-iuc`` shouldn't depend on  ``$TRAVIS_COMMIT_RANGE`` being set - perhaps the call to ``planemo ci_find_repos`` can fall back on a diff to the default branch instead?
