### ISSUE TITLE
SRA-tools FASTQ dump fails when using a file list

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/tools-iuc#970]
and selecting `apply left and right clips` or `Dump only biological reads` for certain identifiers.

Example, have a file that contains this identifier `SRR042817`. These are single ended reads, and the error occurs whether or not I set `split spot by read pairs` to true or false

results in this error / traceback
```
galaxy.tools.parameters.output_collect DEBUG 2016-09-28 12:32:03,946 (1697) Created dynamic collection dataset for path [/galaxy/database/jobs_directory/001/1697/working/SRR042817_4.fastq] with element identifier [SRR042817:4] for output [list_paired] (1695.361 ms)
galaxy.tools.parameters.output_collect DEBUG 2016-09-28 12:32:04,339 (1697) Add dynamic collection datsets to history for output [list_paired] (393.093 ms)
galaxy.tools.parameters.output_collect ERROR 2016-09-28 12:32:04,369 Problem gathering output collection.
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/tools/parameters/output_collect.py", line 65, in collect_dynamic_collections
    collection_builder.populate()
  File "/galaxy/lib/galaxy/dataset_collections/builder.py", line 87, in populate
    elements = self.build_elements()
  File "/galaxy/lib/galaxy/dataset_collections/builder.py", line 58, in build_elements
    new_elements[identifier] = element.build()
  File "/galaxy/lib/galaxy/dataset_collections/builder.py", line 64, in build
    collection = build_collection( type_plugin, self.build_elements() )
  File "/galaxy/lib/galaxy/dataset_collections/builder.py", line 12, in build_collection
    set_collection_elements( dataset_collection, type, dataset_instances )
  File "/galaxy/lib/galaxy/dataset_collections/builder.py", line 19, in set_collection_elements
    for element in type.generate_elements( dataset_instances ):
  File "/galaxy/lib/galaxy/dataset_collections/types/paired.py", line 24, in generate_elements
    self._validation_failed( INVALID_IDENTIFIERS_MESSAGE )
  File "/galaxy/lib/galaxy/dataset_collections/types/__init__.py", line 23, in _validation_failed
    raise exceptions.ObjectAttributeInvalidException( message )
ObjectAttributeInvalidException: Paired instance must define 'forward' and 'reverse' datasets .
```

Worse yet, I end up with an empty green 'single-end fasta|q' list and a forever "running" yellow 'Paired end fastq' list. No user feedback is available.

**Comment by blankenberg** [comment]
Directory status with "Dump only biological reads":
```
.:
total 3.3M
drwxr-xr-x 4 dan dan   97 Dec 19 14:58 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 14:58 ..
-rw-r--r-- 1 dan dan  136 Dec 19 14:58 conda_activate.log
drwx------ 2 dan dan   39 Dec 19 14:58 .ncbi
drwxr-xr-x 2 dan dan   34 Dec 19 14:58 sra
-rw-r--r-- 1 dan dan 3.3M Dec 19 14:58 SRR042817_4.fastq

./.ncbi:
total 4.0K
drwx------ 2 dan dan  39 Dec 19 14:58 .
drwxr-xr-x 4 dan dan  97 Dec 19 14:58 ..
-rw------- 1 dan dan 904 Dec 19 14:58 user-settings.mkfg

./sra:
total 13M
drwxr-xr-x 2 dan dan  34 Dec 19 14:58 .
drwxr-xr-x 4 dan dan  97 Dec 19 14:58 ..
-rw-r--r-- 1 dan dan 13M Dec 19 14:58 SRR042817.sra


<mv file loop>

.:
total 3.3M
drwxr-xr-x 4 dan dan   97 Dec 19 14:58 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 14:58 ..
-rw-r--r-- 1 dan dan  136 Dec 19 14:58 conda_activate.log
drwx------ 2 dan dan   39 Dec 19 14:58 .ncbi
drwxr-xr-x 2 dan dan   34 Dec 19 14:58 sra
-rw-r--r-- 1 dan dan 3.3M Dec 19 14:58 SRR042817_4.fastq

./.ncbi:
total 4.0K
drwx------ 2 dan dan  39 Dec 19 14:58 .
drwxr-xr-x 4 dan dan  97 Dec 19 14:58 ..
-rw------- 1 dan dan 904 Dec 19 14:58 user-settings.mkfg

./sra:
total 13M
drwxr-xr-x 2 dan dan  34 Dec 19 14:58 .
drwxr-xr-x 4 dan dan  97 Dec 19 14:58 ..
-rw-r--r-- 1 dan dan 13M Dec 19 14:58 SRR042817.sra
```

without the flag set:
```
.:
total 7.3M
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw-r--r-- 1 dan dan  136 Dec 19 15:00 conda_activate.log
drwx------ 2 dan dan   39 Dec 19 15:00 .ncbi
drwxr-xr-x 2 dan dan   34 Dec 19 15:00 sra
-rw-r--r-- 1 dan dan 545K Dec 19 15:00 SRR042817_1.fastq
-rw-r--r-- 1 dan dan 3.2M Dec 19 15:00 SRR042817_2.fastq
-rw-r--r-- 1 dan dan 403K Dec 19 15:00 SRR042817_3.fastq
-rw-r--r-- 1 dan dan 3.3M Dec 19 15:00 SRR042817_4.fastq

./.ncbi:
total 8.0K
drwx------ 2 dan dan   39 Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw------- 1 dan dan  904 Dec 19 15:00 user-settings.mkfg

./sra:
total 13M
drwxr-xr-x 2 dan dan   34 Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw-r--r-- 1 dan dan  13M Dec 19 15:00 SRR042817.sra

<mv files loop>

.:
total 7.3M
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw-r--r-- 1 dan dan  136 Dec 19 15:00 conda_activate.log
drwx------ 2 dan dan   39 Dec 19 15:00 .ncbi
drwxr-xr-x 2 dan dan   34 Dec 19 15:00 sra
-rw-r--r-- 1 dan dan 403K Dec 19 15:00 SRR042817_3.fastq
-rw-r--r-- 1 dan dan 3.3M Dec 19 15:00 SRR042817_4.fastq
-rw-r--r-- 1 dan dan 545K Dec 19 15:00 SRR042817_forward.fastq
-rw-r--r-- 1 dan dan 3.2M Dec 19 15:00 SRR042817_reverse.fastq

./.ncbi:
total 8.0K
drwx------ 2 dan dan   39 Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw------- 1 dan dan  904 Dec 19 15:00 user-settings.mkfg

./sra:
total 13M
drwxr-xr-x 2 dan dan   34 Dec 19 15:00 .
drwxr-xr-x 4 dan dan 4.0K Dec 19 15:00 ..
-rw-r--r-- 1 dan dan  13M Dec 19 15:00 SRR042817.sra
```

**Comment by blankenberg** [comment]
When not setting any flags, the outputs created seem oddish:
forward (the adaptors?):
```
@GF0N05X04JZ0W0_key_seqeuence_adaptor/1
TCAG
+SRR042817.1 GF0N05X04JZ0W0 length=4
FFFF
@GF0N05X04IALOX_key_seqeuence_adaptor/1
TCAGTGGAACCACCCGTC
+SRR042817.2 GF0N05X04IALOX length=18
IIIIIIIIIIIIHHHIII
@GF0N05X04JXCMM_key_seqeuence_adaptor/1
TCAG
+SRR042817.3 GF0N05X04JXCMM length=4
BBB:
```

reverse (barcodes?):
```
@GF0N05X04JZ0W0_barcode/2
TGGAACCAC
+SRR042817.1 GF0N05X04JZ0W0 length=9
FFFFFFFFF
@GF0N05X04IALOX_barcode/2
AATTCCTTTGAGTTTTAGCCTTGCGGCCGTACTCCCCAGGCGGGGCGCTTAATGCGTTAGCTACGGCACAGACTGCAAACACACAGCCCACACCTAGCGCCCACCGTTTACAGCATGGACTACCAGGGTATCTAATCCTGTTCGCTCCCCATGCTTTCGCTCCTCAGCGTCAGTAACTGCCCAGTAACCTGCCTTCGCCATCGGTGTTCCTCCTGATATCTGCGCATTTCACCGCTACACCCAGGAATTCCAGTTACCCCTACAGCACTCTAGTCGTGCCCGTATCGCCTGCACGCCCGGAGTTAAGCCCCGGAATTTCACAGACGACGCGACACACCACCTACGAGCTCTTTACGCCCAGTAAATCCGGACAACGCTTGCACCCTACGTATTACCGCGGCTGCTGGCACGTAGTTAGCCGGCGCTTCTTCTCCACGGTACCGTCACCCACCAAGGTGGGCGTTCGTCCCGGCGAAGGAGTTACACCGAAGCCGTCATCCCCACGCGGCGTCGCTGCATCAGGCTTGCGC
+SRR042817.2 GF0N05X04IALOX length=530
IIIIIIHHHIFB6666DIIIIIIIIIIIIIIIICCCCIIII>>>>IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHHHIIIIIIIHHHIIIIIIIIIIHHHIIIIHHHIIIIIIIIIIIIIIIIHHHIIIIIIIIIIIIIIIIIICCCCIIIIGGGIIIIIIIIIIIIIIIIIIIIIIHHHIIIIIIIIIIIIIIIIIIIIIIH>>>IIIIIIIIIIIIIIIIIIEEB?61119AA50///:ADDD8888AB>551133??6DDGIIIIIIIIIIIIHHHIIIIIIIIIIIIGDAAAAAAAAAAAI@@@@II<<<<BAAADGE66666BDDDDBEAA<99BA=CAAA?911159??>>CCCBEHE;;;;;8DDCCCCC??555>>>7>>A445;;;8>A>??CC:8888::877740..--00020/147466848:;::86403-,,2-.,,,,,,,,,,,,/2.,,,,,,1,,,,1244,,,,,,,,,,,21.1122258-868::9=::47799995,,,,,15/,
@GF0N05X04JXCMM_barcode/2
TGGAACCAC
+SRR042817.3 GF0N05X04JXCMM length=9
666<<<=<?
@GF0N05X04I3HS9_barcode/2
AATTCATTTAAGTTTCAACCTTGCGGTCGTACCTCCCCAGGCGGAGTGCTTAATGCGTTAGCTGCGGCACTAAACCCCGGAAAGGGTCTAACACCTAGCACTCATCGTTTACGGCGTGGACTACCAGGGTATCTAATCCTGTTTGCTCCCCACGCTTTCGAGCCTCAGCGTCAGTTACAAGCCAGAGAGCCGCTTTCGCCACCGGTGTTCCTCCATATATCTACGCATTTCACCGCTACACATGGAATTCCACTCCTCCCTCTTGCACTCAAGTTAAACAGTTTCCAAAGCGTAACTATGGTTAAGCCCGACAGCCCTTTAACTTCAGACTTTATCTAACCGCCTGCGCTCGCTTTACGCCCAATAAATCCGGACAACGCTCGGGACCTCGTATTACCGCGGCTGCTGGCACGTAGTTAGCCGTCCCTTTCTGGTAAGATACCGTCACAGTGTGAACTTTCCACTCTTCACACTCGTTCTCTCTTACAACAGAGCTTACGATCCGAAAACCTTCTTCA
+SRR042817.4 GF0N05X04I3HS9 length=518
GGD:990..;6/,,,/.266667>>>??>=><883332426766:87344888<998<<<?>>>>==8934211....11,,,2224444<ABDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF===FFFFFFFFFFFE???FFFAAAAFFFF666DFFFFFDFFFFFF???CCFCCCCAFFFCCDDFFF@@@FFFFFFDDDFDD??666CFFFFFDDDFFFFF?666;DFFDAAAAAA<9000.2155753112,..6/2237:<<<;23001189:@888>>8;;99000008<><<<<923/..../<<1,../4A=70047???00/44988@>=>::=?BD8888<;88;;;2....3.,,,0055756667632.//:;8323;:<<;::::;;;886::66656:988888::12---0./--33.02000.003420..00.00200,,,779420044684---2788577777:777402--,,00.3.00,,,,,,,,,,,,,.3
```

Perhaps this is a bad record?

**Comment by Takadonet** [comment]
Can you confirm that it will fix your issue please.

**Comment by lldelisle** [comment]
Hi,
This issue is fixed in the fasterq-dump tool as sra which will have more than 2 fastqs will be put in a special collection. For the fastq-dump tool, I would recommend to always put Dump only biological reads as the other reads are adaptors.
