### ISSUE TITLE
package_tiff_4_0_3 not installing (tiff download URL not working)

### ISSUE THREAD

**Issue by afgane** [galaxyproject/tools-iuc#996]
Looks like the download ftp site for tiff is down (and has been for a few weeks since I've been seeing this error that long):
```
Updating an existing record for version 4.0.3 of tool dependency tiff for revision 1720cc7e1949 of repository package_tiff_4_0_3 by updating the status from Uninstalled to Installing.
tool_shed.galaxy_install.tool_dependencies.recipe.step_handler DEBUG 2016-10-13 16:14:30,236 Attempting to download via url: ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.3.tar.gz
tool_shed.galaxy_install.install_manager ERROR 2016-10-13 16:14:30,250 Error installing tool dependency tiff version 4.0.3.
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 125, in install_and_build_package_via_fabric
    tool_dependency = self.install_and_build_package( install_environment, tool_dependency, actions_dict )
  File "/mnt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/install_manager.py", line 83, in install_and_build_package
    initial_download=True )
  File "/mnt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 31, in execute_step
    initial_download=initial_download )
  File "/mnt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 688, in execute_step
    dir = self.url_download( work_dir, downloaded_filename, url, extract=True, checksums=checksums )
  File "/mnt/galaxy/galaxy-app/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 184, in url_download
    raise Exception( err_msg )
Exception: Error downloading from URL
ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.3.tar.gz:
<urlopen error [Errno -2] Name or service not known>
tool_shed.util.tool_dependency_util DEBUG 2016-10-13 16:14:30,253 Updating an existing record for version 4.0.3 of tool dependency tiff for revision 1720cc7e1949 of repository package_tiff_4_0_3 by updating the status from Installing to Error.
```

Possibly just changing the the download source to something like this URL would fix this: http://download.osgeo.org/libtiff/

(here's a reference to the package that's influenced by this: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_tiff_4_0_3)

**Comment by nsoranzo** [comment]
That was already fixed here in #213, but never reached the TS. I've uploaded it now.
